package next

// PaymentIntentNextActionKonbiniStoresFamilymart FamilyMart instruction details.
type PaymentIntentNextActionKonbiniStoresFamilymart struct {
	PaymentIntentNextActionKonbiniFamilymart *PaymentIntentNextActionKonbiniFamilymart
}
