package next

// PaymentIntentNextActionKonbiniStoresLawson Lawson instruction details.
type PaymentIntentNextActionKonbiniStoresLawson struct {
	PaymentIntentNextActionKonbiniLawson *PaymentIntentNextActionKonbiniLawson
}
