package next

// PaymentIntentNextActionKonbiniStoresSeicomart Seicomart instruction details.
type PaymentIntentNextActionKonbiniStoresSeicomart struct {
	PaymentIntentNextActionKonbiniSeicomart *PaymentIntentNextActionKonbiniSeicomart
}
