/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PostProductsProductVariantsRequestOptionsInner struct {

	// The ID of the Product Option to set the value for.
	OptionId string `json:"option_id"`

	// The value to give for the Product Option.
	Value string `json:"value"`
}
