/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PostOrdersOrderClaimsRequestClaimItemsInner struct {

	// The ID of the Line Item that will be claimed.
	ItemId string `json:"item_id"`

	// The number of items that will be returned
	Quantity int32 `json:"quantity"`

	// Short text describing the Claim Item in further detail.
	Note string `json:"note,omitempty"`

	// The reason for the Claim
	Reason string `json:"reason,omitempty"`

	// A list o tags to add to the Claim Item
	Tags []string `json:"tags,omitempty"`

	// A list of image URL's that will be associated with the Claim
	Images []string `json:"images,omitempty"`
}
