/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PostShippingOptionsRequest struct {

	// The name of the Shipping Option
	Name string `json:"name"`

	// The ID of the Region in which the Shipping Option will be available.
	RegionId string `json:"region_id"`

	// The ID of the Fulfillment Provider that handles the Shipping Option.
	ProviderId string `json:"provider_id"`

	// The ID of the Shipping Profile to add the Shipping Option to.
	ProfileId float32 `json:"profile_id,omitempty"`

	// The data needed for the Fulfillment Provider to handle shipping with this Shipping Option.
	Data map[string]interface{} `json:"data"`

	// The type of the Shipping Option price.
	PriceType string `json:"price_type"`

	// The amount to charge for the Shipping Option.
	Amount int32 `json:"amount,omitempty"`

	// The requirements that must be satisfied for the Shipping Option to be available.
	Requirements []PostShippingOptionsRequestRequirementsInner `json:"requirements,omitempty"`

	// Whether the Shipping Option defines a return shipment.
	IsReturn bool `json:"is_return,omitempty"`

	// If true, the option can be used for draft orders
	AdminOnly bool `json:"admin_only,omitempty"`

	// An optional set of key-value pairs with additional information.
	Metadata map[string]interface{} `json:"metadata,omitempty"`

	// [EXPERIMENTAL] Tax included in prices of shipping option
	IncludesTax bool `json:"includes_tax,omitempty"`
}
