/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PostAppsRequest struct {

	// Name of the application for the token to be generated for.
	ApplicationName string `json:"application_name"`

	// State of the application.
	State string `json:"state"`

	// The code for the generated token.
	Code string `json:"code"`
}
