/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PostUsersUserPasswordRequest struct {

	// The Users email.
	Email string `json:"email,omitempty"`

	// The token generated from the 'password-token' endpoint.
	Token string `json:"token"`

	// The Users new password.
	Password string `json:"password"`
}
