/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PostDraftOrdersDraftOrderLineItemsItemRequest struct {

	// The potential custom price of the item.
	UnitPrice int32 `json:"unit_price,omitempty"`

	// The potential custom title of the item.
	Title string `json:"title,omitempty"`

	// The quantity of the Line Item.
	Quantity int32 `json:"quantity,omitempty"`

	// The optional key-value map with additional details about the Line Item.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
}
