/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PostBatchJobsRequest struct {

	// The type of batch job to start.
	Type string `json:"type"`

	// Additional infomration regarding the batch to be used for processing.
	Context map[string]interface{} `json:"context"`

	// Set a batch job in dry_run mode to get some information on what will be done without applying any modifications.
	DryRun bool `json:"dry_run,omitempty"`
}
