/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type PostDiscountsRequest struct {

	// A unique code that will be used to redeem the Discount
	Code string `json:"code"`

	// Whether the Discount should have multiple instances of itself, each with a different code. This can be useful for automatically generated codes that all have to follow a common set of rules.
	IsDynamic bool `json:"is_dynamic,omitempty"`

	Rule PostDiscountsRequestRule `json:"rule"`

	// Whether the Discount code is disabled on creation. You will have to enable it later to make it available to Customers.
	IsDisabled bool `json:"is_disabled,omitempty"`

	// The time at which the Discount should be available.
	StartsAt time.Time `json:"starts_at,omitempty"`

	// The time at which the Discount should no longer be available.
	EndsAt time.Time `json:"ends_at,omitempty"`

	// Duration the discount runs between
	ValidDuration string `json:"valid_duration,omitempty"`

	// A list of Region ids representing the Regions in which the Discount can be used.
	Regions []string `json:"regions,omitempty"`

	// Maximum times the discount can be used
	UsageLimit float32 `json:"usage_limit,omitempty"`

	// An optional set of key-value pairs to hold additional information.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
}
