/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PostCustomersCustomerRequest struct {

	// The Customer's email.
	Email string `json:"email,omitempty"`

	// The Customer's first name.
	FirstName string `json:"first_name,omitempty"`

	// The Customer's last name.
	LastName string `json:"last_name,omitempty"`

	// The Customer's phone number.
	Phone string `json:"phone,omitempty"`

	// The Customer's password.
	Password string `json:"password,omitempty"`

	// A list of customer groups to which the customer belongs.
	Groups []PostCustomersCustomerRequestGroupsInner `json:"groups,omitempty"`

	// An optional set of key-value pairs to hold additional information.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
}
