/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PostApps400Response struct {

	// A slug code to indicate the type of the error.
	Code string `json:"code,omitempty"`

	Message string `json:"message,omitempty"`

	// A slug indicating the type of the error.
	Type string `json:"type,omitempty"`

	// Array of errors
	Errors []ModelError `json:"errors,omitempty"`
}
