/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PostOrdersOrderFulfillmentsRequestItemsInner struct {

	// The ID of Line Item to fulfill.
	ItemId string `json:"item_id"`

	// The quantity of the Line Item to fulfill.
	Quantity int32 `json:"quantity"`
}
