/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PostOrdersOrderClaimsClaimRequestClaimItemsInner struct {

	// The ID of the Claim Item.
	Id string `json:"id"`

	// The ID of the Line Item that will be claimed.
	ItemId string `json:"item_id,omitempty"`

	// The number of items that will be returned
	Quantity int32 `json:"quantity,omitempty"`

	// Short text describing the Claim Item in further detail.
	Note string `json:"note,omitempty"`

	// The reason for the Claim
	Reason string `json:"reason,omitempty"`

	// A list o tags to add to the Claim Item
	Tags []PostOrdersOrderClaimsClaimRequestClaimItemsInnerTagsInner `json:"tags"`

	// A list of image URL's that will be associated with the Claim
	Images []PostOrdersOrderClaimsClaimRequestClaimItemsInnerImagesInner `json:"images"`

	// An optional set of key-value pairs to hold additional information.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
}
