/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PostProductsProductVariantsVariantRequest struct {

	// The title to identify the Product Variant by.
	Title string `json:"title,omitempty"`

	// The unique SKU for the Product Variant.
	Sku string `json:"sku,omitempty"`

	// The EAN number of the item.
	Ean string `json:"ean,omitempty"`

	// The UPC number of the item.
	Upc string `json:"upc,omitempty"`

	// A generic GTIN field for the Product Variant.
	Barcode string `json:"barcode,omitempty"`

	// The Harmonized System code for the Product Variant.
	HsCode string `json:"hs_code,omitempty"`

	// The amount of stock kept for the Product Variant.
	InventoryQuantity int32 `json:"inventory_quantity,omitempty"`

	// Whether the Product Variant can be purchased when out of stock.
	AllowBackorder bool `json:"allow_backorder,omitempty"`

	// Whether Medusa should keep track of the inventory for this Product Variant.
	ManageInventory bool `json:"manage_inventory,omitempty"`

	// The weight of the Product Variant.
	Weight float32 `json:"weight,omitempty"`

	// The length of the Product Variant.
	Length float32 `json:"length,omitempty"`

	// The height of the Product Variant.
	Height float32 `json:"height,omitempty"`

	// The width of the Product Variant.
	Width float32 `json:"width,omitempty"`

	// The country of origin of the Product Variant.
	OriginCountry string `json:"origin_country,omitempty"`

	// The Manufacturer Identification code for the Product Variant.
	MidCode string `json:"mid_code,omitempty"`

	// The material composition of the Product Variant.
	Material string `json:"material,omitempty"`

	// An optional set of key-value pairs with additional information.
	Metadata map[string]interface{} `json:"metadata,omitempty"`

	Prices []PostProductsProductVariantsRequestPricesInner `json:"prices"`

	Options []PostProductsProductVariantsRequestOptionsInner `json:"options,omitempty"`
}
