/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PostDiscountsDiscountDynamicCodesRequest struct {

	// The unique code that will be used to redeem the Discount.
	Code string `json:"code"`

	// amount of times the discount can be applied.
	UsageLimit float32 `json:"usage_limit,omitempty"`

	// An optional set of key-value paris to hold additional information.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
}
