/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PostOrdersOrderSwapsRequest struct {

	// The Line Items to return as part of the Swap.
	ReturnItems []PostOrdersOrderSwapsRequestReturnItemsInner `json:"return_items"`

	ReturnShipping PostOrdersOrderSwapsRequestReturnShipping `json:"return_shipping,omitempty"`

	// The new items to send to the Customer.
	AdditionalItems []PostOrdersOrderClaimsRequestAdditionalItemsInner `json:"additional_items,omitempty"`

	// The custom shipping options to potentially create a Shipping Method from.
	CustomShippingOptions []PostOrdersOrderSwapsRequestCustomShippingOptionsInner `json:"custom_shipping_options,omitempty"`

	// If set to true no notification will be send related to this Swap.
	NoNotification bool `json:"no_notification,omitempty"`

	// If true, swaps can be completed with items out of stock
	AllowBackorder bool `json:"allow_backorder,omitempty"`
}
