/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PostProductsProductRequest struct {

	// The title of the Product
	Title string `json:"title,omitempty"`

	// The subtitle of the Product
	Subtitle string `json:"subtitle,omitempty"`

	// A description of the Product.
	Description string `json:"description,omitempty"`

	// A flag to indicate if discounts can be applied to the LineItems generated from this Product
	Discountable bool `json:"discountable,omitempty"`

	// Images of the Product.
	Images []string `json:"images,omitempty"`

	// The thumbnail to use for the Product.
	Thumbnail string `json:"thumbnail,omitempty"`

	// A unique handle to identify the Product by.
	Handle string `json:"handle,omitempty"`

	// The status of the product.
	Status string `json:"status,omitempty"`

	Type PostProductsRequestType `json:"type,omitempty"`

	// The ID of the Collection the Product should belong to.
	CollectionId string `json:"collection_id,omitempty"`

	// Tags to associate the Product with.
	Tags []PostProductsRequestTagsInner `json:"tags,omitempty"`

	// [EXPERIMENTAL] Sales channels to associate the Product with.
	SalesChannels []PostProductsRequestSalesChannelsInner `json:"sales_channels,omitempty"`

	// A list of Product Variants to create with the Product.
	Variants []PostProductsProductRequestVariantsInner `json:"variants,omitempty"`

	// The wieght of the Product.
	Weight float32 `json:"weight,omitempty"`

	// The length of the Product.
	Length float32 `json:"length,omitempty"`

	// The height of the Product.
	Height float32 `json:"height,omitempty"`

	// The width of the Product.
	Width float32 `json:"width,omitempty"`

	// The country of origin of the Product.
	OriginCountry string `json:"origin_country,omitempty"`

	// The Manufacturer Identification code for the Product.
	MidCode string `json:"mid_code,omitempty"`

	// The material composition of the Product.
	Material string `json:"material,omitempty"`

	// An optional set of key-value pairs with additional information.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
}
