/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// PostDiscountsRequestRule - The Discount Rule that defines how Discounts are calculated
type PostDiscountsRequestRule struct {

	// A short description of the discount
	Description string `json:"description,omitempty"`

	// The type of the Discount, can be `fixed` for discounts that reduce the price by a fixed amount, `percentage` for percentage reductions or `free_shipping` for shipping vouchers.
	Type string `json:"type"`

	// The value that the discount represents; this will depend on the type of the discount
	Value float32 `json:"value"`

	// The scope that the discount should apply to.
	Allocation string `json:"allocation"`

	// A set of conditions that can be used to limit when  the discount can be used. Only one of `products`, `product_types`, `product_collections`, `product_tags`, and `customer_groups` should be provided.
	Conditions []PostDiscountsRequestRuleConditionsInner `json:"conditions,omitempty"`
}
