/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PostStoreRequest struct {

	// The name of the Store
	Name string `json:"name,omitempty"`

	// A template for Swap links - use `{{cart_id}}` to insert the Swap Cart id
	SwapLinkTemplate string `json:"swap_link_template,omitempty"`

	// A template for payment links links - use `{{cart_id}}` to insert the Cart id
	PaymentLinkTemplate string `json:"payment_link_template,omitempty"`

	// A template for invite links - use `{{invite_token}}` to insert the invite token
	InviteLinkTemplate string `json:"invite_link_template,omitempty"`

	// The default currency code for the Store.
	DefaultCurrencyCode string `json:"default_currency_code,omitempty"`

	// Array of currencies in 2 character ISO code format.
	Currencies []string `json:"currencies,omitempty"`

	// An optional set of key-value pairs with additional information.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
}
