/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PostPriceListsPriceListRequest struct {

	// The name of the Price List
	Name string `json:"name"`

	// A description of the Price List.
	Description string `json:"description"`

	// The date with timezone that the Price List starts being valid.
	StartsAt string `json:"starts_at,omitempty"`

	// The date with timezone that the Price List ends being valid.
	EndsAt string `json:"ends_at,omitempty"`

	// The type of the Price List.
	Type string `json:"type"`

	// The status of the Price List.
	Status string `json:"status,omitempty"`

	// The prices of the Price List.
	Prices []PostPriceListsPriceListRequestPricesInner `json:"prices"`

	// A list of customer groups that the Price List applies to.
	CustomerGroups []PostCustomersCustomerRequestGroupsInner `json:"customer_groups,omitempty"`

	// [EXPERIMENTAL] Tax included in prices of price list
	IncludesTax bool `json:"includes_tax,omitempty"`
}
