/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PostSalesChannelsSalesChannelRequest struct {

	// Name of the sales channel.
	Name string `json:"name,omitempty"`

	// Sales Channel description.
	Description string `json:"description,omitempty"`

	// Indication of if the sales channel is active.
	IsDisabled bool `json:"is_disabled,omitempty"`
}
