/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type PostGiftCardsRequest struct {

	// The value (excluding VAT) that the Gift Card should represent.
	Value int32 `json:"value,omitempty"`

	// Whether the Gift Card is disabled on creation. You will have to enable it later to make it available to Customers.
	IsDisabled bool `json:"is_disabled,omitempty"`

	// The time at which the Gift Card should no longer be available.
	EndsAt time.Time `json:"ends_at,omitempty"`

	// The ID of the Region in which the Gift Card can be used.
	RegionId string `json:"region_id"`

	// An optional set of key-value pairs to hold additional information.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
}
