/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PostNotesRequest struct {

	// The ID of the resource which the Note relates to.
	ResourceId string `json:"resource_id"`

	// The type of resource which the Note relates to.
	ResourceType string `json:"resource_type"`

	// The content of the Note to create.
	Value string `json:"value"`
}
