/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PostSalesChannelsRequest struct {

	// The name of the Sales Channel
	Name string `json:"name"`

	// The description of the Sales Channel
	Description string `json:"description,omitempty"`

	// Whether the Sales Channel is disabled or not.
	IsDisabled bool `json:"is_disabled,omitempty"`
}
