/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PostShippingOptionsOptionRequest struct {

	// The name of the Shipping Option
	Name string `json:"name,omitempty"`

	// The amount to charge for the Shipping Option.
	Amount int32 `json:"amount,omitempty"`

	// If true, the option can be used for draft orders
	AdminOnly bool `json:"admin_only,omitempty"`

	// An optional set of key-value pairs with additional information.
	Metadata map[string]interface{} `json:"metadata,omitempty"`

	// The requirements that must be satisfied for the Shipping Option to be available.
	Requirements []PostShippingOptionsOptionRequestRequirementsInner `json:"requirements"`

	// [EXPERIMENTAL] Tax included in prices of shipping option
	IncludesTax bool `json:"includes_tax,omitempty"`
}
