/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// PostOrdersOrderClaimsRequestReturnShipping - Optional details for the Return Shipping Method, if the items are to be sent back.
type PostOrdersOrderClaimsRequestReturnShipping struct {

	// The ID of the Shipping Option to create the Shipping Method from.
	OptionId string `json:"option_id,omitempty"`

	// The price to charge for the Shipping Method.
	Price int32 `json:"price,omitempty"`
}
