/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PostOrdersOrderRefundsRequest struct {

	// The amount to refund.
	Amount int32 `json:"amount"`

	// The reason for the Refund.
	Reason string `json:"reason"`

	// A note with additional details about the Refund.
	Note string `json:"note,omitempty"`

	// If set to true no notification will be send related to this Refund.
	NoNotification bool `json:"no_notification,omitempty"`
}
