/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// PostOrdersOrderRequestShippingMethod - The Shipping Method used for shipping the order.
type PostOrdersOrderRequestShippingMethod struct {

	// The ID of the shipping provider.
	ProviderId string `json:"provider_id,omitempty"`

	// The ID of the shipping profile.
	ProfileId string `json:"profile_id,omitempty"`

	// The price of the shipping.
	Price int32 `json:"price,omitempty"`

	// Data relevant to the specific shipping method.
	Data map[string]interface{} `json:"data,omitempty"`

	// Items to ship
	Items []LineItem `json:"items,omitempty"`
}
