/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PostPriceListsPriceListPricesBatchRequest struct {

	// The prices to update or add.
	Prices []PostPriceListsPriceListPricesBatchRequestPricesInner `json:"prices,omitempty"`

	// If true the prices will replace all existing prices associated with the Price List.
	Override bool `json:"override,omitempty"`
}
