/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PostDraftOrdersRequest struct {

	// The status of the draft order
	Status string `json:"status,omitempty"`

	// The email of the customer of the draft order
	Email string `json:"email"`

	BillingAddress Address `json:"billing_address,omitempty"`

	ShippingAddress Address `json:"shipping_address,omitempty"`

	// The Line Items that have been received.
	Items []PostDraftOrdersRequestItemsInner `json:"items"`

	// The ID of the region for the draft order
	RegionId string `json:"region_id"`

	// The discounts to add on the draft order
	Discounts []PostDraftOrdersRequestDiscountsInner `json:"discounts,omitempty"`

	// The ID of the customer to add on the draft order
	CustomerId string `json:"customer_id,omitempty"`

	// An optional flag passed to the resulting order to determine use of notifications.
	NoNotificationOrder bool `json:"no_notification_order,omitempty"`

	// The shipping methods for the draft order
	ShippingMethods []PostDraftOrdersRequestShippingMethodsInner `json:"shipping_methods"`

	// The optional key-value map with additional details about the Draft Order.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
}
