/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PostReturnReasonsRequest struct {

	// The label to display to the Customer.
	Label string `json:"label"`

	// The value that the Return Reason will be identified by. Must be unique.
	Value string `json:"value"`

	// The ID of the parent return reason.
	ParentReturnReasonId string `json:"parent_return_reason_id,omitempty"`

	// An optional description to for the Reason.
	Description string `json:"description,omitempty"`

	// An optional set of key-value pairs with additional information.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
}
