/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PostOrdersOrderShippingMethodsRequest struct {

	// The price (excluding VAT) that should be charged for the Shipping Method
	Price int32 `json:"price"`

	// The ID of the Shipping Option to create the Shipping Method from.
	OptionId string `json:"option_id"`

	// The data required for the Shipping Option to create a Shipping Method. This will depend on the Fulfillment Provider.
	Data map[string]interface{} `json:"data,omitempty"`
}
