/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PostCustomersRequest struct {

	// The customer's email.
	Email string `json:"email"`

	// The customer's first name.
	FirstName string `json:"first_name"`

	// The customer's last name.
	LastName string `json:"last_name"`

	// The customer's password.
	Password string `json:"password"`

	// The customer's phone number.
	Phone string `json:"phone,omitempty"`

	// An optional set of key-value pairs to hold additional information.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
}
