/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PostTaxRatesRequest struct {

	// A code to identify the tax type by
	Code string `json:"code"`

	// A human friendly name for the tax
	Name string `json:"name"`

	// The ID of the Region that the rate belongs to
	RegionId string `json:"region_id"`

	// The numeric rate to charge
	Rate float32 `json:"rate,omitempty"`

	// The IDs of the products associated with this tax rate
	Products []string `json:"products,omitempty"`

	// The IDs of the shipping options associated with this tax rate
	ShippingOptions []string `json:"shipping_options,omitempty"`

	// The IDs of the types of products associated with this tax rate
	ProductTypes []string `json:"product_types,omitempty"`
}
