package settings

// InvoiceSettingQuoteSetting
type InvoiceSettingQuoteSetting struct {
	// Number of days within which a customer must pay invoices generated by this quote. This value will be `null` for quotes where `collection_method=charge_automatically`.
	DaysUntilDue int `json:"days_until_due,omitempty"`
}
