package settings

import "github.com/driver005/gateway/core"

// InvoiceSettingQuoteSetting
type InvoiceSettingQuoteSetting struct {
	core.Model

	// Number of days within which a customer must pay invoices generated by this quote. This value will be `null` for quotes where `collection_method=charge_automatically`.
	DaysUntilDue int `json:"days_until_due,omitempty"`
}
