/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// GetReturns - List Returns
func GetReturns(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostOrdersOrderReturns - Request a Return
func PostOrdersOrderReturns(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostReturnsReturnCancel - Cancel a Return
func PostReturnsReturnCancel(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostReturnsReturnReceive - Receive a Return
func PostReturnsReturnReceive(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
