/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// DeletePriceListsPriceList - Delete a Price List
func DeletePriceListsPriceList(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// DeletePriceListsPriceListPricesBatch - Delete Prices
func DeletePriceListsPriceListPricesBatch(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// DeletePriceListsPriceListProductsProductPrices - Delete Product's Prices
func DeletePriceListsPriceListProductsProductPrices(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// DeletePriceListsPriceListVariantsVariantPrices - Delete Variant's Prices
func DeletePriceListsPriceListVariantsVariantPrices(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetPriceLists - List Price Lists
func GetPriceLists(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetPriceListsPriceList - Get a Price List
func GetPriceListsPriceList(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostPriceListsPriceList - Create a Price List
func PostPriceListsPriceList(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostPriceListsPriceListPriceList - Update a Price List
func PostPriceListsPriceListPriceList(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostPriceListsPriceListPricesBatch - Update Prices
func PostPriceListsPriceListPricesBatch(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
