/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// DeleteShippingOptionsOption - Delete a Shipping Option
func DeleteShippingOptionsOption(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetShippingOptions - List Shipping Options
func GetShippingOptions(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetShippingOptionsOption - Get a Shipping Option
func GetShippingOptionsOption(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostShippingOptions - Create Shipping Option
func PostShippingOptions(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostShippingOptionsOption - Update Shipping Option
func PostShippingOptionsOption(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
