/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// GetOrders - List Orders
func GetOrders(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetOrdersOrder - Get an Order
func GetOrdersOrder(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostOrdersOrder - Update an Order
func PostOrdersOrder(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostOrdersOrderArchive - Archive Order
func PostOrdersOrderArchive(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostOrdersOrderCancel - Cancel an Order
func PostOrdersOrderCancel(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostOrdersOrderCapture - Capture Order's Payment
func PostOrdersOrderCapture(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostOrdersOrderComplete - Complete an Order
func PostOrdersOrderComplete(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostOrdersOrderRefunds - Create a Refund
func PostOrdersOrderRefunds(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostOrdersOrderReturns - Request a Return
func PostOrdersOrderReturns(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostOrdersOrderShipment - Create a Shipment
func PostOrdersOrderShipment(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostOrdersOrderShippingMethods - Add a Shipping Method
func PostOrdersOrderShippingMethods(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
