/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// DeleteTaxRatesTaxRate - Delete a Tax Rate
func DeleteTaxRatesTaxRate(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// DeleteTaxRatesTaxRateProductTypes - Delete from Product Types
func DeleteTaxRatesTaxRateProductTypes(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// DeleteTaxRatesTaxRateProducts - Delete from Products
func DeleteTaxRatesTaxRateProducts(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// DeleteTaxRatesTaxRateShippingOptions - Del. for Shipping Options
func DeleteTaxRatesTaxRateShippingOptions(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetTaxRates - List Tax Rates
func GetTaxRates(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetTaxRatesTaxRate - Get a Tax Rate
func GetTaxRatesTaxRate(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostTaxRates - Create a Tax Rate
func PostTaxRates(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostTaxRatesTaxRate - Update a Tax Rate
func PostTaxRatesTaxRate(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostTaxRatesTaxRateProductTypes - Add to Product Types
func PostTaxRatesTaxRateProductTypes(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostTaxRatesTaxRateProducts - Add to Products
func PostTaxRatesTaxRateProducts(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostTaxRatesTaxRateShippingOptions - Add to Shipping Options
func PostTaxRatesTaxRateShippingOptions(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
