/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// GetSwaps - List Swaps
func GetSwaps(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetSwapsSwap - Get a Swap
func GetSwapsSwap(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostOrdersOrderSwaps - Create a Swap
func PostOrdersOrderSwaps(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostOrdersOrderSwapsSwapProcessPayment - Process Swap Payment
func PostOrdersOrderSwapsSwapProcessPayment(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostOrdersOrderSwapsSwapShipments - Create Swap Shipment
func PostOrdersOrderSwapsSwapShipments(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostOrdersSwapCancel - Cancels a Swap
func PostOrdersSwapCancel(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
