/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// PostOrdersClaimFulfillmentsCancel - Cancel Claim Fulfillment
func PostOrdersClaimFulfillmentsCancel(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostOrdersOrderClaimsClaimFulfillments - Create Claim Fulfillment
func PostOrdersOrderClaimsClaimFulfillments(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostOrdersOrderFulfillments - Create a Fulfillment
func PostOrdersOrderFulfillments(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostOrdersOrderFulfillmentsCancel - Cancels a Fulfilmment
func PostOrdersOrderFulfillmentsCancel(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostOrdersOrderSwapsSwapFulfillments - Create Swap Fulfillment
func PostOrdersOrderSwapsSwapFulfillments(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostOrdersSwapFulfillmentsCancel - Cancel Swap's Fulfilmment
func PostOrdersSwapFulfillmentsCancel(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
