/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// DeleteInvitesInvite - Create an Invite
func DeleteInvitesInvite(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetInvites - Lists Invites
func GetInvites(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostInvites - Create an Invite
func PostInvites(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostInvitesInviteAccept - Accept an Invite
func PostInvitesInviteAccept(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostInvitesInviteResend - Resend an Invite
func PostInvitesInviteResend(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
