/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// DeleteReturnReason - Delete a Return Reason
func DeleteReturnReason(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetReturnReasons - List Return Reasons
func GetReturnReasons(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetReturnReasonsReason - Get a Return Reason
func GetReturnReasonsReason(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostReturnReasons - Create a Return Reason
func PostReturnReasons(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostReturnReasonsReason - Update a Return Reason
func PostReturnReasonsReason(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
