/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// DeleteDraftOrdersDraftOrder - Delete a Draft Order
func DeleteDraftOrdersDraftOrder(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// DeleteDraftOrdersDraftOrderLineItemsItem - Delete a Line Item
func DeleteDraftOrdersDraftOrderLineItemsItem(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetDraftOrders - List Draft Orders
func GetDraftOrders(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetDraftOrdersDraftOrder - Get a Draft Order
func GetDraftOrdersDraftOrder(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostDraftOrders - Create a Draft Order
func PostDraftOrders(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostDraftOrdersDraftOrder - Update a Draft Order
func PostDraftOrdersDraftOrder(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostDraftOrdersDraftOrderLineItems - Create a Line Item
func PostDraftOrdersDraftOrderLineItems(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostDraftOrdersDraftOrderLineItemsItem - Update a Line Item
func PostDraftOrdersDraftOrderLineItemsItem(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostDraftOrdersDraftOrderRegisterPayment - Registers a Payment
func PostDraftOrdersDraftOrderRegisterPayment(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
