/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// DeleteGiftCardsGiftCard - Delete a Gift Card
func DeleteGiftCardsGiftCard(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetGiftCards - List Gift Cards
func GetGiftCards(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetGiftCardsGiftCard - Get a Gift Card
func GetGiftCardsGiftCard(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostGiftCards - Create a Gift Card
func PostGiftCards(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostGiftCardsGiftCard - Update a Gift Card
func PostGiftCardsGiftCard(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
