/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// DeleteSalesChannelsChannelProductsBatch - Delete Products
func DeleteSalesChannelsChannelProductsBatch(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// DeleteSalesChannelsSalesChannel - Delete a Sales Channel
func DeleteSalesChannelsSalesChannel(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetSalesChannels - List Sales Channels
func GetSalesChannels(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetSalesChannelsSalesChannel - Get a Sales Channel
func GetSalesChannelsSalesChannel(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostSalesChannels - Create a Sales Channel
func PostSalesChannels(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostSalesChannelsChannelProductsBatch - Add Products
func PostSalesChannelsChannelProductsBatch(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostSalesChannelsSalesChannel - Update a Sales Channel
func PostSalesChannelsSalesChannel(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
