/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// DeleteRegionsRegion - Delete a Region
func DeleteRegionsRegion(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetRegions - List Regions
func GetRegions(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetRegionsRegion - Get a Region
func GetRegionsRegion(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetRegionsRegionFulfillmentOptions - List Fulfillment Options
func GetRegionsRegionFulfillmentOptions(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostRegions - Create a Region
func PostRegions(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostRegionsRegion - Update a Region
func PostRegionsRegion(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostRegionsRegionCountries - Add Country
func PostRegionsRegionCountries(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostRegionsRegionCountriesCountry - Delete Country
func PostRegionsRegionCountriesCountry(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostRegionsRegionFulfillmentProviders - Add Fulfillment Provider
func PostRegionsRegionFulfillmentProviders(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostRegionsRegionFulfillmentProvidersProvider - Del. Fulfillment Provider
func PostRegionsRegionFulfillmentProvidersProvider(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostRegionsRegionPaymentProviders - Add Payment Provider
func PostRegionsRegionPaymentProviders(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostRegionsRegionPaymentProvidersProvider - Delete Payment Provider
func PostRegionsRegionPaymentProvidersProvider(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
