/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// DeleteStoreCurrenciesCode - Delete a Currency Code
func DeleteStoreCurrenciesCode(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetStore - Get Store details
func GetStore(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetStorePaymentProviders - List Payment Providers
func GetStorePaymentProviders(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetStoreTaxProviders - List Tax Providers
func GetStoreTaxProviders(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostStore - Update Store Details
func PostStore(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostStoreCurrenciesCode - Add a Currency Code
func PostStoreCurrenciesCode(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
