/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// DeleteUsersUser - Delete a User
func DeleteUsersUser(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetUsers - List Users
func GetUsers(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetUsersUser - Get a User
func GetUsersUser(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostUsers - Create a User
func PostUsers(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostUsersUser - Update a User
func PostUsersUser(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostUsersUserPassword - Reset Password
func PostUsersUserPassword(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostUsersUserPasswordToken - Request Password Reset
func PostUsersUserPasswordToken(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
