/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// DeleteCollectionsCollection - Delete a Collection
func DeleteCollectionsCollection(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// DeleteProductsFromCollection - Remove Product
func DeleteProductsFromCollection(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetCollections - List Collections
func GetCollections(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetCollectionsCollection - Get a Collection
func GetCollectionsCollection(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostCollections - Create a Collection
func PostCollections(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostCollectionsCollection - Update a Collection
func PostCollectionsCollection(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostProductsToCollection - Update Products
func PostProductsToCollection(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
