/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// DeleteDiscountsDiscount - Delete a Discount
func DeleteDiscountsDiscount(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// DeleteDiscountsDiscountDynamicCodesCode - Delete a Dynamic Code
func DeleteDiscountsDiscountDynamicCodesCode(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// DeleteDiscountsDiscountRegionsRegion - Remove Region
func DeleteDiscountsDiscountRegionsRegion(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetDiscounts - List Discounts
func GetDiscounts(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetDiscountsDiscount - Get a Discount
func GetDiscountsDiscount(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetDiscountsDiscountCode - Get Discount by Code
func GetDiscountsDiscountCode(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostDiscounts - Creates a Discount
func PostDiscounts(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostDiscountsDiscount - Update a Discount
func PostDiscountsDiscount(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostDiscountsDiscountConditionsCondition - Update a Condition
func PostDiscountsDiscountConditionsCondition(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostDiscountsDiscountDynamicCodes - Create a Dynamic Code
func PostDiscountsDiscountDynamicCodes(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostDiscountsDiscountRegionsRegion - Add Region
func PostDiscountsDiscountRegionsRegion(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
