/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// DeleteNotesNote - Delete a Note
func DeleteNotesNote(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetNotes - List Notes
func GetNotes(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetNotesNote - Get a Note
func GetNotesNote(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostNotes - Creates a Note
func PostNotes(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostNotesNote - Update a Note
func PostNotesNote(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
