package subscription

import (
	"github.com/driver005/gateway/billing/subscription/subscriptions"
	"github.com/driver005/gateway/billing/subscriptionSchedule"
	"github.com/driver005/gateway/core"
	"github.com/driver005/gateway/internal/customer"
	setupIntent "github.com/driver005/gateway/internal/setup/intent"
	"github.com/driver005/gateway/payment/method"
	"github.com/driver005/gateway/products/discount"
	"github.com/driver005/gateway/products/price"
	"github.com/driver005/gateway/utils/tax"
	"github.com/google/uuid"
)

// SubscriptionBillingThresholds
type SubscriptionBillingThresholds struct {
	core.Model

	// Monetary threshold that triggers the subscription to create an invoice
	AmountGte int `json:"amount_gte,omitempty"`
	// Indicates if the `billing_cycle_anchor` should be reset when a threshold is reached. If true, `billing_cycle_anchor` will be updated to the date/time the threshold was last reached; otherwise, the value will remain unchanged. This value may not be `true` if the subscription contains items with plans that have `aggregate_usage=last_ever`.
	ResetBillingCycleAnchor bool `json:"reset_billing_cycle_anchor,omitempty"`
	// Usage threshold that triggers the subscription to create an invoice
	UsageGte int `json:"usage_gte,omitempty"`
}

// SubscriptionPendingInvoiceItemInterval
type SubscriptionPendingInvoiceItemInterval struct {
	core.Model

	// Specifies invoicing frequency. Either `day`, `week`, `month` or `year`.
	Interval string `json:"interval,omitempty"`
	// The number of intervals between invoices. For example, `interval=month` and `interval_count=3` bills every 3 months. Maximum of one year interval allowed (1 year, 12 months, or 52 weeks).
	IntervalCount int `json:"interval_count,omitempty"`
}

// Subscription Subscriptions allow you to charge a customer on a recurring basis.  Related guide: [Creating Subscriptions](https://stripe.com/docs/billing/subscriptions/creating).
type Subscription struct {
	core.Model

	AutomaticTax bool `json:"automatic_tax,omitempty"`
	// Determines the date of the first full invoice, and, for plans with `month` or `year` intervals, the day of the month for subsequent invoices. The timestamp is in UTC format.
	BillingCycleAnchor int                            `json:"billing_cycle_anchor,omitempty"`
	BillingThresholds  *SubscriptionBillingThresholds `json:"billing_thresholds,omitempty" database:"foreignKey:id"`
	// A date in the future at which the subscription will automatically get canceled
	CancelAt int `json:"cancel_at,omitempty"`
	// If the subscription has been canceled with the `at_period_end` flag set to `true`, `cancel_at_period_end` on the subscription will be true. You can use this attribute to determine whether a subscription that has a status of active is scheduled to be canceled at the end of the current period.
	CancelAtPeriodEnd bool `json:"cancel_at_period_end,omitempty"`
	// If the subscription has been canceled, the date of that cancellation. If the subscription was canceled with `cancel_at_period_end`, `canceled_at` will reflect the time of the most recent update request, not the end of the subscription period when the subscription is automatically moved to a canceled state.
	CanceledAt int `json:"canceled_at,omitempty"`
	// Either `charge_automatically`, or `send_invoice`. When charging automatically, Stripe will attempt to pay this subscription at the end of the cycle using the default source attached to the customer. When sending an invoice, Stripe will email your customer an invoice with payment instructions and mark the subscription as `active`.
	CollectionMethod string `json:"collection_method,omitempty"`
	// Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. Must be a [supported currency](https://stripe.com/docs/currencies).
	Currency string `json:"currency,omitempty"`
	// End of the current period that the subscription has been invoiced for. At the end of this period, a new invoice will be created.
	CurrentPeriodEnd int `json:"current_period_end,omitempty"`
	// Start of the current period that the subscription has been invoiced for.
	CurrentPeriodStart int `json:"current_period_start,omitempty"`
	// Number of days a customer has to pay invoices generated by this subscription. This value will be `null` for subscriptions where `collection_method=charge_automatically`.
	DaysUntilDue int `json:"days_until_due,omitempty"`
	// The tax rates that will apply to any subscription item that does not have `tax_rates` set. Invoices created will have their `default_tax_rates` populated from the subscription.
	DefaultTaxRates *tax.TaxRate `json:"default_tax_rates,omitempty" database:"foreignKey:id"`
	// The subscription's description, meant to be displayable to the customer. Use this field to optionally store an explanation of the subscription for rendering in Stripe surfaces.
	Description string             `json:"description,omitempty"`
	Discount    *discount.Discount `json:"discount,omitempty" database:"foreignKey:id"`
	// If the subscription has ended, the date the subscription ended.
	EndedAt int `json:"ended_at,omitempty"`
	// Specifies the approximate timestamp on which any pending invoice items will be billed according to the schedule provided at `pending_invoice_item_interval`.
	NextPendingInvoiceItemInvoice int                                                 `json:"next_pending_invoice_item_invoice,omitempty"`
	PendingInvoiceItemInterval    *SubscriptionPendingInvoiceItemInterval             `json:"pending_invoice_item_interval,omitempty" database:"foreignKey:id"`
	PaymentSettings               *subscriptions.SubscriptionsResourcePaymentSettings `json:"payment_settings,omitempty" database:"foreignKey:id"`
	PauseCollection               *subscriptions.SubscriptionsResourcePauseCollection `json:"pause_collection,omitempty" database:"foreignKey:id"`
	PendingUpdate                 *subscriptions.SubscriptionsResourcePendingUpdate   `json:"pending_update,omitempty" database:"foreignKey:id"`
	// Date when the subscription was first created. The date might differ from the `created` date due to backdating.
	StartDate int `json:"start_date,omitempty"`
	// Possible values are `incomplete`, `incomplete_expired`, `trialing`, `active`, `past_due`, `canceled`, or `unpaid`.   For `collection_method=charge_automatically` a subscription moves into `incomplete` if the initial payment attempt fails. A subscription in this state can only have metadata and default_source updated. Once the first invoice is paid, the subscription moves into an `active` state. If the first invoice is not paid within 23 hours, the subscription transitions to `incomplete_expired`. This is a terminal state, the open invoice will be voided and no further invoices will be generated.   A subscription that is currently in a trial period is `trialing` and moves to `active` when the trial period is over.   If subscription `collection_method=charge_automatically` it becomes `past_due` when payment to renew it fails and `canceled` or `unpaid` (depending on your subscriptions settings) when Stripe has exhausted all payment retry attempts.   If subscription `collection_method=send_invoice` it becomes `past_due` when its invoice is not paid by the due date, and `canceled` or `unpaid` if it is still not paid by an additional deadline after that. Note that when a subscription has a status of `unpaid`, no subsequent invoices will be attempted (invoices will be created, but then immediately automatically closed). After receiving updated payment information from a customer, you may choose to reopen and pay their closed invoices.
	Status string `json:"status,omitempty"`
	// If the subscription has a trial, the end of that trial.
	TrialEnd int `json:"trial_end,omitempty"`
	// If the subscription has a trial, the beginning of that trial.
	TrialStart int `json:"trial_start,omitempty"`

	CustomerId             *uuid.UUID            `json:"customer_id,omitempty" swaggerignore:"true"`
	Customer               *customer.Customer    `json:"customer,omitempty" database:"foreignKey:customer_id"`
	DefaultPaymentMethodId *uuid.UUID            `json:"default_payment_method_id,omitempty" swaggerignore:"true"`
	DefaultPaymentMethod   *method.PaymentMethod `json:"default_payment_method,omitempty" database:"foreignKey:default_payment_method_id"`
	// LatestInvoiceId        *uuid.UUID                                  `json:"latest_invoice_id,omitempty" swaggerignore:"true"`
	// LatestInvoice          *invoice.Invoice                           `json:"latest_invoice,omitempty" database:"foreignKey:latest_invoice_id"`
	PendingSetupIntentId *uuid.UUID                                 `json:"pending_setup_intent_id,omitempty" swaggerignore:"true"`
	PendingSetupIntent   *setupIntent.SetupIntent                   `json:"pending_setup_intent,omitempty" database:"foreignKey:pending_setup_intent_id"`
	PriceId              *uuid.UUID                                 `json:"price_id,omitempty" swaggerignore:"true"`
	Price                *price.Price                               `json:"price,omitempty" database:"foreignKey:price_id"`
	ScheduleId           *uuid.UUID                                 `json:"schedule_id,omitempty" swaggerignore:"true"`
	Schedule             *subscriptionSchedule.SubscriptionSchedule `json:"schedule,omitempty" database:"foreignKey:schedule_id"`
}
