/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type DeleteProductsFromCollection200Response struct {

	// The ID of the collection
	Id string `json:"id,omitempty"`

	// The type of object the removal was executed on
	Object string `json:"object,omitempty"`

	// The IDs of the products removed from the collection
	RemovedProducts []string `json:"removed_products,omitempty"`
}
