package details

// PaymentMethodDetailsBancontactGeneratedSepaDebit The ID of the SEPA Direct Debit PaymentMethod which was generated by this Charge.
type PaymentMethodDetailsBancontactGeneratedSepaDebit struct {
	// PaymentMethod *PaymentMethod
	// string        *string
}
