package details

import "github.com/driver005/gateway/models"

// PaymentMethodDetailsBancontactGeneratedSepaDebitMandate The mandate for the SEPA Direct Debit PaymentMethod which was generated by this Charge.
type PaymentMethodDetailsBancontactGeneratedSepaDebitMandate struct {
	Mandate *models.Mandate
	string  string
}
