package details

import "github.com/driver005/gateway/core"

// PaymentMethodDetailsGrabpay
type PaymentMethodDetailsGrabpay struct {
	core.Model

	// Unique transaction id generated by GrabPay
	TransactionId string `json:"transaction_id,omitempty"`
}
