package details

import "github.com/driver005/gateway/core"

// PaymentMethodDetailsPix
type PaymentMethodDetailsPix struct {
	core.Model

	// Unique transaction id generated by BCB
	BankTransactionId string `json:"bank_transaction_id,omitempty"`
}
