package details

import "github.com/driver005/gateway/core"

// PaymentMethodDetailsPromptpay
type PaymentMethodDetailsPromptpay struct {
	core.Model

	// Bill reference generated by PromptPay
	Reference string `json:"reference,omitempty"`
}
