/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

// DiscountRule - Holds the rules that governs how a Discount is calculated when applied to a Cart.
type DiscountRule struct {

	// The discount rule's ID
	Id string `json:"id,omitempty"`

	// The type of the Discount, can be `fixed` for discounts that reduce the price by a fixed amount, `percentage` for percentage reductions or `free_shipping` for shipping vouchers.
	Type string `json:"type"`

	// A short description of the discount
	Description string `json:"description,omitempty"`

	// The value that the discount represents; this will depend on the type of the discount
	Value int32 `json:"value"`

	// The scope that the discount should apply to.
	Allocation string `json:"allocation,omitempty"`

	// A set of conditions that can be used to limit when  the discount can be used. Available if the relation `conditions` is expanded.
	Conditions []map[string]interface{} `json:"conditions,omitempty"`

	// The date with timezone at which the resource was created.
	CreatedAt time.Time `json:"created_at,omitempty"`

	// The date with timezone at which the resource was updated.
	UpdatedAt time.Time `json:"updated_at,omitempty"`

	// The date with timezone at which the resource was deleted.
	DeletedAt time.Time `json:"deleted_at,omitempty"`

	// An optional key-value map with additional details
	Metadata map[string]interface{} `json:"metadata,omitempty"`
}
