/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

// CustomShippingOption - Custom Shipping Options are 'overriden' Shipping Options. Store managers can attach a Custom Shipping Option to a cart in order to set a custom price for a particular Shipping Option
type CustomShippingOption struct {

	// The custom shipping option's ID
	Id string `json:"id,omitempty"`

	// The custom price set that will override the shipping option's original price
	Price int32 `json:"price"`

	// The ID of the Shipping Option that the custom shipping option overrides
	ShippingOptionId string `json:"shipping_option_id"`

	// A shipping option object. Available if the relation `shipping_option` is expanded.
	ShippingOption map[string]interface{} `json:"shipping_option,omitempty"`

	// The ID of the Cart that the custom shipping option is attached to
	CartId string `json:"cart_id,omitempty"`

	// A cart object. Available if the relation `cart` is expanded.
	Cart map[string]interface{} `json:"cart,omitempty"`

	// The date with timezone at which the resource was created.
	CreatedAt time.Time `json:"created_at,omitempty"`

	// The date with timezone at which the resource was updated.
	UpdatedAt time.Time `json:"updated_at,omitempty"`

	// The date with timezone at which the resource was deleted.
	DeletedAt time.Time `json:"deleted_at,omitempty"`

	// An optional key-value map with additional details
	Metadata map[string]interface{} `json:"metadata,omitempty"`

	// [EXPERIMENTAL] Indicates if the custom shipping option price include tax
	IncludesTax bool `json:"includes_tax,omitempty"`
}
