/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

// ProductCollection - Product Collections represents a group of Products that are related.
type ProductCollection struct {

	// The product collection's ID
	Id string `json:"id,omitempty"`

	// The title that the Product Collection is identified by.
	Title string `json:"title"`

	// A unique string that identifies the Product Collection - can for example be used in slug structures.
	Handle string `json:"handle,omitempty"`

	// The Products contained in the Product Collection. Available if the relation `products` is expanded.
	Products []map[string]interface{} `json:"products,omitempty"`

	// The date with timezone at which the resource was created.
	CreatedAt time.Time `json:"created_at,omitempty"`

	// The date with timezone at which the resource was updated.
	UpdatedAt time.Time `json:"updated_at,omitempty"`

	// The date with timezone at which the resource was deleted.
	DeletedAt time.Time `json:"deleted_at,omitempty"`

	// An optional key-value map with additional details
	Metadata map[string]interface{} `json:"metadata,omitempty"`
}
