/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PriceListPricesInner struct {

	// The customer group's ID
	Id string `json:"id,omitempty"`

	// The 3 character currency code that the Money Amount is given in.
	CurrencyCode string `json:"currency_code"`

	Currency Currency `json:"currency,omitempty"`

	// The amount in the smallest currecny unit (e.g. cents 100 cents to charge $1) that the Product Variant will cost.
	Amount int32 `json:"amount"`

	// The minimum quantity that the Money Amount applies to. If this value is not set, the Money Amount applies to all quantities.
	MinQuantity int32 `json:"min_quantity,omitempty"`

	// The maximum quantity that the Money Amount applies to. If this value is not set, the Money Amount applies to all quantities.
	MaxQuantity int32 `json:"max_quantity,omitempty"`

	// The ID of the price list associated with the money amount
	PriceListId string `json:"price_list_id,omitempty"`

	PriceList PriceList `json:"price_list,omitempty"`

	// The id of the Product Variant contained in the Line Item.
	VariantId string `json:"variant_id,omitempty"`

	// The Product Variant contained in the Line Item. Available if the relation `variant` is expanded.
	Variant map[string]interface{} `json:"variant,omitempty"`

	// The region's ID
	RegionId string `json:"region_id,omitempty"`

	// A region object. Available if the relation `region` is expanded.
	Region map[string]interface{} `json:"region,omitempty"`

	// The date with timezone at which the resource was created.
	CreatedAt time.Time `json:"created_at,omitempty"`

	// The date with timezone at which the resource was updated.
	UpdatedAt time.Time `json:"updated_at,omitempty"`

	// The date with timezone at which the resource was deleted.
	DeletedAt time.Time `json:"deleted_at,omitempty"`

	// An optional key-value map with additional details
	Metadata map[string]interface{} `json:"metadata,omitempty"`

	// The name of the customer group
	Name string `json:"name"`

	// The customers that belong to the customer group. Available if the relation `customers` is expanded.
	Customers []map[string]interface{} `json:"customers,omitempty"`

	// The price lists that are associated with the customer group. Available if the relation `price_lists` is expanded.
	PriceLists []PriceList `json:"price_lists,omitempty"`
}
