/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Country - Country details
type Country struct {

	// The country's ID
	Id string `json:"id,omitempty"`

	// The 2 character ISO code of the country in lower case
	Iso2 string `json:"iso_2"`

	// The 2 character ISO code of the country in lower case
	Iso3 string `json:"iso_3"`

	// The numerical ISO code for the country.
	NumCode string `json:"num_code"`

	// The normalized country name in upper case.
	Name string `json:"name"`

	// The country name appropriate for display.
	DisplayName string `json:"display_name"`

	// The region ID this country is associated with.
	RegionId string `json:"region_id,omitempty"`

	// A region object. Available if the relation `region` is expanded.
	Region map[string]interface{} `json:"region,omitempty"`
}
