/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

// BatchJob - A Batch Job.
type BatchJob struct {

	// The unique identifier for the batch job.
	Id string `json:"id,omitempty"`

	// The type of batch job.
	Type string `json:"type"`

	// The status of the batch job.
	Status string `json:"status,omitempty"`

	// The unique identifier of the user that created the batch job.
	CreatedBy string `json:"created_by,omitempty"`

	// A user object. Available if the relation `created_by_user` is expanded.
	CreatedByUser map[string]interface{} `json:"created_by_user,omitempty"`

	// The context of the batch job, the type of the batch job determines what the context should contain.
	Context map[string]interface{} `json:"context,omitempty"`

	// Specify if the job must apply the modifications or not.
	DryRun bool `json:"dry_run,omitempty"`

	Result BatchJobResult `json:"result,omitempty"`

	// The date from which the job has been pre processed.
	PreProcessedAt time.Time `json:"pre_processed_at,omitempty"`

	// The date the job is processing at.
	ProcessingAt time.Time `json:"processing_at,omitempty"`

	// The date when the confirmation has been done.
	ConfirmedAt time.Time `json:"confirmed_at,omitempty"`

	// The date of the completion.
	CompletedAt time.Time `json:"completed_at,omitempty"`

	// The date of the concellation.
	CanceledAt time.Time `json:"canceled_at,omitempty"`

	// The date when the job failed.
	FailedAt time.Time `json:"failed_at,omitempty"`

	// The date with timezone at which the resource was created.
	CreatedAt time.Time `json:"created_at,omitempty"`

	// The date with timezone at which the resource was last updated.
	UpdatedAt time.Time `json:"updated_at,omitempty"`

	// The date with timezone at which the resource was deleted.
	DeletedAt time.Time `json:"deleted_at,omitempty"`
}
