/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// ReturnItem - Correlates a Line Item with a Return, keeping track of the quantity of the Line Item that will be returned.
type ReturnItem struct {

	// The id of the Return that the Return Item belongs to.
	ReturnId string `json:"return_id"`

	ReturnOrder ModelReturn `json:"return_order,omitempty"`

	// The id of the Line Item that the Return Item references.
	ItemId string `json:"item_id"`

	Item LineItem `json:"item,omitempty"`

	// The quantity of the Line Item that is included in the Return.
	Quantity int32 `json:"quantity,omitempty"`

	// Whether the Return Item was requested initially or received unexpectedly in the warehouse.
	IsRequested bool `json:"is_requested,omitempty"`

	// The quantity that was originally requested to be returned.
	RequestedQuantity int32 `json:"requested_quantity,omitempty"`

	// The quantity that was received in the warehouse.
	RecievedQuantity int32 `json:"recieved_quantity,omitempty"`

	// The ID of the reason for returning the item.
	ReasonId string `json:"reason_id,omitempty"`

	Reason ReturnReason `json:"reason,omitempty"`

	// An optional note with additional details about the Return.
	Note string `json:"note,omitempty"`

	// An optional key-value map with additional details
	Metadata map[string]interface{} `json:"metadata,omitempty"`
}
