/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

// NotificationResend - A resend of a Notification.
type NotificationResend struct {

	// The notification resend's ID
	Id string `json:"id,omitempty"`

	// The name of the event that the notification was sent for.
	EventName string `json:"event_name,omitempty"`

	// The type of resource that the Notification refers to.
	ResourceType string `json:"resource_type,omitempty"`

	// The ID of the resource that the Notification refers to.
	ResourceId string `json:"resource_id,omitempty"`

	// The ID of the Customer that the Notification was sent to.
	CustomerId string `json:"customer_id,omitempty"`

	// A customer object. Available if the relation `customer` is expanded.
	Customer map[string]interface{} `json:"customer,omitempty"`

	// The address that the Notification was sent to. This will usually be an email address, but represent other addresses such as a chat bot user id
	To string `json:"to,omitempty"`

	// The data that the Notification was sent with. This contains all the data necessary for the Notification Provider to initiate a resend.
	Data map[string]interface{} `json:"data,omitempty"`

	// The ID of the Notification that was originally sent.
	ParentId string `json:"parent_id,omitempty"`

	ParentNotification Notification `json:"parent_notification,omitempty"`

	// The ID of the Notification Provider that handles the Notification.
	ProviderId string `json:"provider_id,omitempty"`

	Provider NotificationProvider `json:"provider,omitempty"`

	// The date with timezone at which the resource was created.
	CreatedAt time.Time `json:"created_at,omitempty"`

	// The date with timezone at which the resource was updated.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
}
