/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// OrderItemChange - Represents an order edit item change
type OrderItemChange struct {

	// The order item change's ID
	Id string `json:"id,omitempty"`

	// The order's status
	Type string `json:"type"`

	// The ID of the order edit
	OrderEditId string `json:"order_edit_id"`

	OrderEdit OrderEdit `json:"order_edit,omitempty"`

	// The ID of the original line item in the order
	OriginalLineItemId string `json:"original_line_item_id,omitempty"`

	OriginalLineItem LineItem `json:"original_line_item,omitempty"`

	// The ID of the cloned line item.
	LineItemId string `json:"line_item_id,omitempty"`

	LineItem LineItem `json:"line_item,omitempty"`
}
