/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

// GiftCardTransaction - Gift Card Transactions are created once a Customer uses a Gift Card to pay for their Order
type GiftCardTransaction struct {

	// The gift card transaction's ID
	Id string `json:"id,omitempty"`

	// The ID of the Gift Card that was used in the transaction.
	GiftCardId string `json:"gift_card_id"`

	// A gift card object. Available if the relation `gift_card` is expanded.
	GiftCard map[string]interface{} `json:"gift_card,omitempty"`

	// The ID of the Order that the Gift Card was used to pay for.
	OrderId string `json:"order_id,omitempty"`

	// An order object. Available if the relation `order` is expanded.
	Order map[string]interface{} `json:"order,omitempty"`

	// The amount that was used from the Gift Card.
	Amount int32 `json:"amount"`

	// The date with timezone at which the resource was created.
	CreatedAt time.Time `json:"created_at,omitempty"`

	// Whether the transaction is taxable or not.
	IsTaxable bool `json:"is_taxable,omitempty"`

	// The tax rate of the transaction
	TaxRate float32 `json:"tax_rate,omitempty"`
}
