/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

// TaxRate - A Tax Rate can be used to associate a certain rate to charge on products within a given Region
type TaxRate struct {

	// The tax rate's ID
	Id string `json:"id,omitempty"`

	// The numeric rate to charge
	Rate float32 `json:"rate,omitempty"`

	// A code to identify the tax type by
	Code string `json:"code,omitempty"`

	// A human friendly name for the tax
	Name string `json:"name"`

	// The id of the Region that the rate belongs to
	RegionId string `json:"region_id"`

	// A region object. Available if the relation `region` is expanded.
	Region map[string]interface{} `json:"region,omitempty"`

	// The products that belong to this tax rate. Available if the relation `products` is expanded.
	Products []map[string]interface{} `json:"products,omitempty"`

	// The product types that belong to this tax rate. Available if the relation `product_types` is expanded.
	ProductTypes []map[string]interface{} `json:"product_types,omitempty"`

	// The shipping options that belong to this tax rate. Available if the relation `shipping_options` is expanded.
	ShippingOptions []map[string]interface{} `json:"shipping_options,omitempty"`

	// The count of products
	ProductCount int32 `json:"product_count,omitempty"`

	// The count of product types
	ProductTypeCount int32 `json:"product_type_count,omitempty"`

	// The count of shipping options
	ShippingOptionCount int32 `json:"shipping_option_count,omitempty"`

	// The date with timezone at which the resource was created.
	CreatedAt time.Time `json:"created_at,omitempty"`

	// The date with timezone at which the resource was updated.
	UpdatedAt time.Time `json:"updated_at,omitempty"`

	// An optional key-value map with additional details
	Metadata map[string]interface{} `json:"metadata,omitempty"`
}
