/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

// DraftOrder - Represents a draft order
type DraftOrder struct {

	// The draft order's ID
	Id string `json:"id,omitempty"`

	// The status of the draft order
	Status string `json:"status,omitempty"`

	// The draft order's display ID
	DisplayId string `json:"display_id,omitempty"`

	// The ID of the cart associated with the draft order.
	CartId string `json:"cart_id,omitempty"`

	// A cart object. Available if the relation `cart` is expanded.
	Cart map[string]interface{} `json:"cart,omitempty"`

	// The ID of the order associated with the draft order.
	OrderId string `json:"order_id,omitempty"`

	// An order object. Available if the relation `order` is expanded.
	Order map[string]interface{} `json:"order,omitempty"`

	// The date the draft order was canceled at.
	CanceledAt time.Time `json:"canceled_at,omitempty"`

	// The date the draft order was completed at.
	CompletedAt time.Time `json:"completed_at,omitempty"`

	// Whether to send the customer notifications regarding order updates.
	NoNotificationOrder bool `json:"no_notification_order,omitempty"`

	// Randomly generated key used to continue the completion of the cart associated with the draft order in case of failure.
	IdempotencyKey string `json:"idempotency_key,omitempty"`

	// The date with timezone at which the resource was created.
	CreatedAt time.Time `json:"created_at,omitempty"`

	// The date with timezone at which the resource was updated.
	UpdatedAt time.Time `json:"updated_at,omitempty"`

	// The date with timezone at which the resource was deleted.
	DeletedAt time.Time `json:"deleted_at,omitempty"`

	// An optional key-value map with additional details
	Metadata map[string]interface{} `json:"metadata,omitempty"`
}
