/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// StagedJob - A staged job resource
type StagedJob struct {

	// The staged job's ID
	Id string `json:"id,omitempty"`

	// The name of the event
	EventName string `json:"event_name"`

	// Data necessary for the job
	Data map[string]interface{} `json:"data,omitempty"`
}
