/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

// Discount - Represents a discount that can be applied to a cart for promotional purposes.
type Discount struct {

	// The discount's ID
	Id string `json:"id,omitempty"`

	// A unique code for the discount - this will be used by the customer to apply the discount
	Code string `json:"code"`

	// A flag to indicate if multiple instances of the discount can be generated. I.e. for newsletter discounts
	IsDynamic bool `json:"is_dynamic"`

	// The Discount Rule that governs the behaviour of the Discount
	RuleId string `json:"rule_id,omitempty"`

	Rule DiscountRule `json:"rule,omitempty"`

	// Whether the Discount has been disabled. Disabled discounts cannot be applied to carts
	IsDisabled bool `json:"is_disabled,omitempty"`

	// The Discount that the discount was created from. This will always be a dynamic discount
	ParentDiscountId string `json:"parent_discount_id,omitempty"`

	ParentDiscount Discount `json:"parent_discount,omitempty"`

	// The time at which the discount can be used.
	StartsAt time.Time `json:"starts_at,omitempty"`

	// The time at which the discount can no longer be used.
	EndsAt time.Time `json:"ends_at,omitempty"`

	// Duration the discount runs between
	ValidDuration string `json:"valid_duration,omitempty"`

	// The Regions in which the Discount can be used. Available if the relation `regions` is expanded.
	Regions []map[string]interface{} `json:"regions,omitempty"`

	// The maximum number of times that a discount can be used.
	UsageLimit int32 `json:"usage_limit,omitempty"`

	// The number of times a discount has been used.
	UsageCount int32 `json:"usage_count,omitempty"`

	// The date with timezone at which the resource was created.
	CreatedAt time.Time `json:"created_at,omitempty"`

	// The date with timezone at which the resource was updated.
	UpdatedAt time.Time `json:"updated_at,omitempty"`

	// The date with timezone at which the resource was deleted.
	DeletedAt time.Time `json:"deleted_at,omitempty"`

	// An optional key-value map with additional details
	Metadata map[string]interface{} `json:"metadata,omitempty"`
}
