/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

// OrderEdit - Order edit keeps track of order items changes.
type OrderEdit struct {

	// The order edit's ID
	Id string `json:"id,omitempty"`

	// The ID of the order that is edited
	OrderId string `json:"order_id"`

	Order Order `json:"order"`

	// Line item changes array.
	Changes []OrderItemChange `json:"changes"`

	// An optional note with additional details about the order edit.
	InternalNote string `json:"internal_note,omitempty"`

	// The unique identifier of the user or customer who created the order edit.
	CreatedBy string `json:"created_by"`

	// The unique identifier of the user or customer who requested the order edit.
	RequestedBy string `json:"requested_by,omitempty"`

	// The date with timezone at which the edit was requested.
	RequestedAt time.Time `json:"requested_at,omitempty"`

	// The unique identifier of the user or customer who confirmed the order edit.
	ConfirmedBy string `json:"confirmed_by,omitempty"`

	// The date with timezone at which the edit was confirmed.
	ConfirmedAt time.Time `json:"confirmed_at,omitempty"`

	// The unique identifier of the user or customer who declined the order edit.
	DeclinedBy string `json:"declined_by,omitempty"`

	// The date with timezone at which the edit was declined.
	DeclinedAt time.Time `json:"declined_at,omitempty"`

	// An optional note why  the order edit is declined.
	DeclinedReason string `json:"declined_reason,omitempty"`

	// The subtotal for line items computed from changes.
	Subtotal int32 `json:"subtotal,omitempty"`

	// The total of discount
	DiscountTotal int32 `json:"discount_total,omitempty"`

	// The total of tax
	TaxTotal int32 `json:"tax_total,omitempty"`

	// The total amount of the edited order.
	Total int32 `json:"total,omitempty"`

	// The difference between the total amount of the order and total amount of edited order.
	DifferenceDue int32 `json:"difference_due,omitempty"`

	// Computed line items from the changes.
	Items []LineItem `json:"items,omitempty"`
}
