/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// FulfillmentItem - Correlates a Line Item with a Fulfillment, keeping track of the quantity of the Line Item.
type FulfillmentItem struct {

	// The id of the Fulfillment that the Fulfillment Item belongs to.
	FulfillmentId string `json:"fulfillment_id"`

	// The id of the Line Item that the Fulfillment Item references.
	ItemId string `json:"item_id"`

	// A fulfillment object. Available if the relation `fulfillment` is expanded.
	Fulfillment map[string]interface{} `json:"fulfillment,omitempty"`

	Item LineItem `json:"item,omitempty"`

	// The quantity of the Line Item that is included in the Fulfillment.
	Quantity int32 `json:"quantity"`
}
