/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

// ProductTypeTaxRate - Associates a tax rate with a product type to indicate that the product type is taxed in a certain way
type ProductTypeTaxRate struct {

	// The ID of the Product type
	ProductTypeId string `json:"product_type_id"`

	ProductType ProductType `json:"product_type,omitempty"`

	// The id of the Tax Rate
	RateId string `json:"rate_id"`

	TaxRate TaxRate `json:"tax_rate,omitempty"`

	// The date with timezone at which the resource was created.
	CreatedAt time.Time `json:"created_at,omitempty"`

	// The date with timezone at which the resource was updated.
	UpdatedAt time.Time `json:"updated_at,omitempty"`

	// An optional key-value map with additional details
	Metadata map[string]interface{} `json:"metadata,omitempty"`
}
