/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

// Note - Notes are elements which we can use in association with different resources to allow users to describe additional information in relation to these.
type Note struct {

	// The note's ID
	Id string `json:"id,omitempty"`

	// The type of resource that the Note refers to.
	ResourceType string `json:"resource_type"`

	// The ID of the resource that the Note refers to.
	ResourceId string `json:"resource_id"`

	// The contents of the note.
	Value string `json:"value"`

	// The ID of the author (user)
	AuthorId string `json:"author_id,omitempty"`

	Author User `json:"author,omitempty"`

	// The date with timezone at which the resource was created.
	CreatedAt time.Time `json:"created_at,omitempty"`

	// The date with timezone at which the resource was updated.
	UpdatedAt time.Time `json:"updated_at,omitempty"`

	// The date with timezone at which the resource was deleted.
	DeletedAt time.Time `json:"deleted_at,omitempty"`

	// An optional key-value map with additional details
	Metadata map[string]interface{} `json:"metadata,omitempty"`
}
