/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Store - Holds settings for the Store, such as name, currencies, etc.
type Store struct {

	// The store's ID
	Id string `json:"id,omitempty"`

	// The name of the Store - this may be displayed to the Customer.
	Name string `json:"name,omitempty"`

	// The 3 character currency code that is the default of the store.
	DefaultCurrencyCode string `json:"default_currency_code,omitempty"`

	DefaultCurrency Currency `json:"default_currency,omitempty"`

	// The currencies that are enabled for the Store. Available if the relation `currencies` is expanded.
	Currencies []Currency `json:"currencies,omitempty"`

	// A template to generate Swap links from. Use {{cart_id}} to include the Swap's `cart_id` in the link.
	SwapLinkTemplate string `json:"swap_link_template,omitempty"`

	// A template to generate Payment links from. Use {{cart_id}} to include the payment's `cart_id` in the link.
	PaymentLinkTemplate string `json:"payment_link_template,omitempty"`

	// A template to generate Invite links from
	InviteLinkTemplate string `json:"invite_link_template,omitempty"`

	// The sales channel ID the cart is associated with.
	DefaultSalesChannelId string `json:"default_sales_channel_id,omitempty"`

	// A sales channel object. Available if the relation `default_sales_channel` is expanded.
	DefaultSalesChannel map[string]interface{} `json:"default_sales_channel,omitempty"`

	// An optional key-value map with additional details
	Metadata map[string]interface{} `json:"metadata,omitempty"`
}
