/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

// ReturnReason - A Reason for why a given product is returned. A Return Reason can be used on Return Items in order to indicate why a Line Item was returned.
type ReturnReason struct {

	// The cart's ID
	Id string `json:"id,omitempty"`

	// A description of the Reason.
	Description string `json:"description,omitempty"`

	// A text that can be displayed to the Customer as a reason.
	Label string `json:"label"`

	// The value to identify the reason by.
	Value string `json:"value"`

	// The ID of the parent reason.
	ParentReturnReasonId string `json:"parent_return_reason_id,omitempty"`

	ParentReturnReason ReturnReason `json:"parent_return_reason,omitempty"`

	ReturnReasonChildren ReturnReason `json:"return_reason_children,omitempty"`

	// The date with timezone at which the resource was created.
	CreatedAt time.Time `json:"created_at,omitempty"`

	// The date with timezone at which the resource was updated.
	UpdatedAt time.Time `json:"updated_at,omitempty"`

	// The date with timezone at which the resource was deleted.
	DeletedAt time.Time `json:"deleted_at,omitempty"`

	// An optional key-value map with additional details
	Metadata map[string]interface{} `json:"metadata,omitempty"`
}
