/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// OAuth - Represent an OAuth app
type OAuth struct {

	// The app's ID
	Id string `json:"id"`

	// The app's display name
	DisplayName string `json:"display_name"`

	// The app's name
	ApplicationName string `json:"application_name"`

	// The URL to install the app
	InstallUrl string `json:"install_url,omitempty"`

	// The URL to uninstall the app
	UninstallUrl string `json:"uninstall_url,omitempty"`

	// Any data necessary to the app.
	Data map[string]interface{} `json:"data,omitempty"`
}
