/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

// TrackingLink - Tracking Link holds information about tracking numbers for a Fulfillment. Tracking Links can optionally contain a URL that can be visited to see the status of the shipment.
type TrackingLink struct {

	// The tracking link's ID
	Id string `json:"id,omitempty"`

	// The URL at which the status of the shipment can be tracked.
	Url string `json:"url,omitempty"`

	// The tracking number given by the shipping carrier.
	TrackingNumber string `json:"tracking_number"`

	// The id of the Fulfillment that the Tracking Link references.
	FulfillmentId string `json:"fulfillment_id"`

	Fulfillment Fulfillment `json:"fulfillment,omitempty"`

	// Randomly generated key used to continue the completion of a process in case of failure.
	IdempotencyKey string `json:"idempotency_key,omitempty"`

	// The date with timezone at which the resource was created.
	CreatedAt time.Time `json:"created_at,omitempty"`

	// The date with timezone at which the resource was updated.
	UpdatedAt time.Time `json:"updated_at,omitempty"`

	// The date with timezone at which the resource was deleted.
	DeletedAt time.Time `json:"deleted_at,omitempty"`

	// An optional key-value map with additional details
	Metadata map[string]interface{} `json:"metadata,omitempty"`
}
