/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

// ShippingOptionRequirement - A requirement that a Cart must satisfy for the Shipping Option to be available to the Cart.
type ShippingOptionRequirement struct {

	// The shipping option requirement's ID
	Id string `json:"id,omitempty"`

	// The id of the Shipping Option that the hipping option requirement belongs to
	ShippingOptionId string `json:"shipping_option_id"`

	ShippingOption ShippingOption `json:"shipping_option,omitempty"`

	// The type of the requirement, this defines how the value will be compared to the Cart's total. `min_subtotal` requirements define the minimum subtotal that is needed for the Shipping Option to be available, while the `max_subtotal` defines the maximum subtotal that the Cart can have for the Shipping Option to be available.
	Type string `json:"type"`

	// The amount to compare the Cart subtotal to.
	Amount int32 `json:"amount"`

	// The date with timezone at which the resource was deleted.
	DeletedAt time.Time `json:"deleted_at,omitempty"`
}
