/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

// PriceList - Price Lists represents a set of prices that overrides the default price for one or more product variants.
type PriceList struct {

	// The price list's ID
	Id string `json:"id,omitempty"`

	// The price list's name
	Name string `json:"name"`

	// The price list's description
	Description string `json:"description"`

	// The type of Price List. This can be one of either `sale` or `override`.
	Type string `json:"type,omitempty"`

	// The status of the Price List
	Status string `json:"status,omitempty"`

	// The date with timezone that the Price List starts being valid.
	StartsAt time.Time `json:"starts_at,omitempty"`

	// The date with timezone that the Price List stops being valid.
	EndsAt time.Time `json:"ends_at,omitempty"`

	// The Customer Groups that the Price List applies to. Available if the relation `customer_groups` is expanded.
	CustomerGroups []map[string]interface{} `json:"customer_groups,omitempty"`

	// The Money Amounts that are associated with the Price List. Available if the relation `prices` is expanded.
	Prices []PriceListPricesInner `json:"prices,omitempty"`

	// [EXPERIMENTAL] Does the price list prices include tax
	IncludesTax bool `json:"includes_tax,omitempty"`

	// The date with timezone at which the resource was created.
	CreatedAt time.Time `json:"created_at,omitempty"`

	// The date with timezone at which the resource was updated.
	UpdatedAt time.Time `json:"updated_at,omitempty"`

	// The date with timezone at which the resource was deleted.
	DeletedAt time.Time `json:"deleted_at,omitempty"`
}
