/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

// Customer - Represents a customer
type Customer struct {

	// The customer's ID
	Id string `json:"id,omitempty"`

	// The customer's email
	Email string `json:"email"`

	// The customer's first name
	FirstName string `json:"first_name,omitempty"`

	// The customer's first name
	LastName string `json:"last_name,omitempty"`

	// The customer's billing address ID
	BillingAddressId string `json:"billing_address_id,omitempty"`

	BillingAddress Address `json:"billing_address,omitempty"`

	// Available if the relation `shipping_addresses` is expanded.
	ShippingAddresses []Address `json:"shipping_addresses,omitempty"`

	// The customer's phone number
	Phone string `json:"phone,omitempty"`

	// Whether the customer has an account or not
	HasAccount bool `json:"has_account,omitempty"`

	// Available if the relation `orders` is expanded.
	Orders []map[string]interface{} `json:"orders,omitempty"`

	// The customer groups the customer belongs to. Available if the relation `groups` is expanded.
	Groups []CustomerGroup `json:"groups,omitempty"`

	// The date with timezone at which the resource was created.
	CreatedAt time.Time `json:"created_at,omitempty"`

	// The date with timezone at which the resource was updated.
	UpdatedAt time.Time `json:"updated_at,omitempty"`

	// The date with timezone at which the resource was deleted.
	DeletedAt time.Time `json:"deleted_at,omitempty"`

	// An optional key-value map with additional details
	Metadata map[string]interface{} `json:"metadata,omitempty"`
}
