/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// Route is the information for every URI.
type Route struct {
	// Name is the name of this Route.
	Name        string
	// Method is the string for the HTTP method. ex) GET, POST etc..
	Method      string
	// Pattern is the pattern of the URI.
	Pattern     string
	// HandlerFunc is the handler function of this route.
	HandlerFunc gin.HandlerFunc
}

// Routes is the list of the generated Route.
type Routes []Route

// NewRouter returns a new router.
func NewRouter() *gin.Engine {
	router := gin.Default()
	for _, route := range routes {
		switch route.Method {
		case http.MethodGet:
			router.GET(route.Pattern, route.HandlerFunc)
		case http.MethodPost:
			router.POST(route.Pattern, route.HandlerFunc)
		case http.MethodPut:
			router.PUT(route.Pattern, route.HandlerFunc)
		case http.MethodPatch:
			router.PATCH(route.Pattern, route.HandlerFunc)
		case http.MethodDelete:
			router.DELETE(route.Pattern, route.HandlerFunc)
		}
	}

	return router
}

// Index is the index handler.
func Index(c *gin.Context) {
	c.String(http.StatusOK, "Hello World!")
}

var routes = Routes{
	{
		"Index",
		http.MethodGet,
		"/admin/",
		Index,
	},

	{
		"GetApps",
		http.MethodGet,
		"/admin/apps",
		GetApps,
	},

	{
		"PostApps",
		http.MethodPost,
		"/admin/apps/authorizations",
		PostApps,
	},

	{
		"DeleteAuth",
		http.MethodDelete,
		"/admin/auth",
		DeleteAuth,
	},

	{
		"GetAuth",
		http.MethodGet,
		"/admin/auth",
		GetAuth,
	},

	{
		"PostAuth",
		http.MethodPost,
		"/admin/auth",
		PostAuth,
	},

	{
		"GetBatchJobs",
		http.MethodGet,
		"/admin/batch-jobs",
		GetBatchJobs,
	},

	{
		"GetBatchJobsBatchJob",
		http.MethodGet,
		"/admin/batch-jobs/:id",
		GetBatchJobsBatchJob,
	},

	{
		"PostBatchJobs",
		http.MethodPost,
		"/admin/batch-jobs",
		PostBatchJobs,
	},

	{
		"PostBatchJobsBatchJobCancel",
		http.MethodPost,
		"/admin/batch-jobs/:id/cancel",
		PostBatchJobsBatchJobCancel,
	},

	{
		"PostBatchJobsBatchJobConfirmProcessing",
		http.MethodPost,
		"/admin/batch-jobs/:id/confirm",
		PostBatchJobsBatchJobConfirmProcessing,
	},

	{
		"PostOrdersClaimCancel",
		http.MethodPost,
		"/admin/orders/:id/claims/:claim_id/cancel",
		PostOrdersClaimCancel,
	},

	{
		"PostOrdersOrderClaims",
		http.MethodPost,
		"/admin/order/:id/claims",
		PostOrdersOrderClaims,
	},

	{
		"PostOrdersOrderClaimsClaim",
		http.MethodPost,
		"/admin/order/:id/claims/:claim_id",
		PostOrdersOrderClaimsClaim,
	},

	{
		"PostOrdersOrderClaimsClaimShipments",
		http.MethodPost,
		"/admin/orders/:id/claims/:claim_id/shipments",
		PostOrdersOrderClaimsClaimShipments,
	},

	{
		"DeleteCollectionsCollection",
		http.MethodDelete,
		"/admin/collections/:id",
		DeleteCollectionsCollection,
	},

	{
		"DeleteProductsFromCollection",
		http.MethodDelete,
		"/admin/collections/:id/products/batch",
		DeleteProductsFromCollection,
	},

	{
		"GetCollections",
		http.MethodGet,
		"/admin/collections",
		GetCollections,
	},

	{
		"GetCollectionsCollection",
		http.MethodGet,
		"/admin/collections/:id",
		GetCollectionsCollection,
	},

	{
		"PostCollections",
		http.MethodPost,
		"/admin/collections",
		PostCollections,
	},

	{
		"PostCollectionsCollection",
		http.MethodPost,
		"/admin/collections/:id",
		PostCollectionsCollection,
	},

	{
		"PostProductsToCollection",
		http.MethodPost,
		"/admin/collections/:id/products/batch",
		PostProductsToCollection,
	},

	{
		"GetCurrencies",
		http.MethodGet,
		"/admin/currencies",
		GetCurrencies,
	},

	{
		"PostCurrenciesCurrency",
		http.MethodPost,
		"/admin/currencies/:code",
		PostCurrenciesCurrency,
	},

	{
		"GetCustomers",
		http.MethodGet,
		"/admin/customers",
		GetCustomers,
	},

	{
		"GetCustomersCustomer",
		http.MethodGet,
		"/admin/customers/:id",
		GetCustomersCustomer,
	},

	{
		"PostCustomers",
		http.MethodPost,
		"/admin/customers",
		PostCustomers,
	},

	{
		"PostCustomersCustomer",
		http.MethodPost,
		"/admin/customers/:id",
		PostCustomersCustomer,
	},

	{
		"DeleteCustomerGroupsCustomerGroup",
		http.MethodDelete,
		"/admin/customer-groups/:id",
		DeleteCustomerGroupsCustomerGroup,
	},

	{
		"DeleteCustomerGroupsGroupCustomerBatch",
		http.MethodDelete,
		"/admin/customer-groups/:id/customers/batch",
		DeleteCustomerGroupsGroupCustomerBatch,
	},

	{
		"GetCustomerGroups",
		http.MethodGet,
		"/admin/customer-groups",
		GetCustomerGroups,
	},

	{
		"GetCustomerGroupsGroup",
		http.MethodGet,
		"/admin/customer-groups/:id",
		GetCustomerGroupsGroup,
	},

	{
		"GetCustomerGroupsGroupCustomers",
		http.MethodGet,
		"/admin/customer-groups/:id/customers",
		GetCustomerGroupsGroupCustomers,
	},

	{
		"PostCustomerGroups",
		http.MethodPost,
		"/admin/customer-groups",
		PostCustomerGroups,
	},

	{
		"PostCustomerGroupsGroup",
		http.MethodPost,
		"/admin/customer-groups/:id",
		PostCustomerGroupsGroup,
	},

	{
		"PostCustomerGroupsGroupCustomersBatch",
		http.MethodPost,
		"/admin/customer-groups/:id/customers/batch",
		PostCustomerGroupsGroupCustomersBatch,
	},

	{
		"DeleteDiscountsDiscount",
		http.MethodDelete,
		"/admin/discounts/:id",
		DeleteDiscountsDiscount,
	},

	{
		"DeleteDiscountsDiscountDynamicCodesCode",
		http.MethodDelete,
		"/admin/discounts/:id/dynamic-codes/:code",
		DeleteDiscountsDiscountDynamicCodesCode,
	},

	{
		"DeleteDiscountsDiscountRegionsRegion",
		http.MethodDelete,
		"/admin/discounts/:id/regions/:region_id",
		DeleteDiscountsDiscountRegionsRegion,
	},

	{
		"GetDiscounts",
		http.MethodGet,
		"/admin/discounts",
		GetDiscounts,
	},

	{
		"GetDiscountsDiscount",
		http.MethodGet,
		"/admin/discounts/:id",
		GetDiscountsDiscount,
	},

	{
		"GetDiscountsDiscountCode",
		http.MethodGet,
		"/admin/discounts/code/:code",
		GetDiscountsDiscountCode,
	},

	{
		"PostDiscounts",
		http.MethodPost,
		"/admin/discounts",
		PostDiscounts,
	},

	{
		"PostDiscountsDiscount",
		http.MethodPost,
		"/admin/discounts/:id",
		PostDiscountsDiscount,
	},

	{
		"PostDiscountsDiscountConditionsCondition",
		http.MethodPost,
		"/admin/discounts/:discount_id/conditions/:condition_id",
		PostDiscountsDiscountConditionsCondition,
	},

	{
		"PostDiscountsDiscountDynamicCodes",
		http.MethodPost,
		"/admin/discounts/:id/dynamic-codes",
		PostDiscountsDiscountDynamicCodes,
	},

	{
		"PostDiscountsDiscountRegionsRegion",
		http.MethodPost,
		"/admin/discounts/:id/regions/:region_id",
		PostDiscountsDiscountRegionsRegion,
	},

	{
		"DeleteDiscountsDiscountConditionsCondition",
		http.MethodDelete,
		"/admin/discounts/:discount_id/conditions/:condition_id",
		DeleteDiscountsDiscountConditionsCondition,
	},

	{
		"GetDiscountsDiscountConditionsCondition",
		http.MethodGet,
		"/admin/discounts/:discount_id/conditions/:condition_id",
		GetDiscountsDiscountConditionsCondition,
	},

	{
		"PostDiscountsDiscountConditions",
		http.MethodPost,
		"/admin/discounts/:discount_id/conditions",
		PostDiscountsDiscountConditions,
	},

	{
		"DeleteDraftOrdersDraftOrder",
		http.MethodDelete,
		"/admin/draft-orders/:id",
		DeleteDraftOrdersDraftOrder,
	},

	{
		"DeleteDraftOrdersDraftOrderLineItemsItem",
		http.MethodDelete,
		"/admin/draft-orders/:id/line-items/:line_id",
		DeleteDraftOrdersDraftOrderLineItemsItem,
	},

	{
		"GetDraftOrders",
		http.MethodGet,
		"/admin/draft-orders",
		GetDraftOrders,
	},

	{
		"GetDraftOrdersDraftOrder",
		http.MethodGet,
		"/admin/draft-orders/:id",
		GetDraftOrdersDraftOrder,
	},

	{
		"PostDraftOrders",
		http.MethodPost,
		"/admin/draft-orders",
		PostDraftOrders,
	},

	{
		"PostDraftOrdersDraftOrder",
		http.MethodPost,
		"/admin/admin/draft-orders/:id",
		PostDraftOrdersDraftOrder,
	},

	{
		"PostDraftOrdersDraftOrderLineItems",
		http.MethodPost,
		"/admin/draft-orders/:id/line-items",
		PostDraftOrdersDraftOrderLineItems,
	},

	{
		"PostDraftOrdersDraftOrderLineItemsItem",
		http.MethodPost,
		"/admin/draft-orders/:id/line-items/:line_id",
		PostDraftOrdersDraftOrderLineItemsItem,
	},

	{
		"PostDraftOrdersDraftOrderRegisterPayment",
		http.MethodPost,
		"/admin/draft-orders/:id/pay",
		PostDraftOrdersDraftOrderRegisterPayment,
	},

	{
		"PostOrdersClaimFulfillmentsCancel",
		http.MethodPost,
		"/admin/orders/:id/claims/:claim_id/fulfillments/:fulfillment_id/cancel",
		PostOrdersClaimFulfillmentsCancel,
	},

	{
		"PostOrdersOrderClaimsClaimFulfillments",
		http.MethodPost,
		"/admin/orders/:id/claims/:claim_id/fulfillments",
		PostOrdersOrderClaimsClaimFulfillments,
	},

	{
		"PostOrdersOrderFulfillments",
		http.MethodPost,
		"/admin/orders/:id/fulfillment",
		PostOrdersOrderFulfillments,
	},

	{
		"PostOrdersOrderFulfillmentsCancel",
		http.MethodPost,
		"/admin/orders/:id/fulfillments/:fulfillment_id/cancel",
		PostOrdersOrderFulfillmentsCancel,
	},

	{
		"PostOrdersOrderSwapsSwapFulfillments",
		http.MethodPost,
		"/admin/orders/:id/swaps/:swap_id/fulfillments",
		PostOrdersOrderSwapsSwapFulfillments,
	},

	{
		"PostOrdersSwapFulfillmentsCancel",
		http.MethodPost,
		"/admin/orders/:id/swaps/:swap_id/fulfillments/:fulfillment_id/cancel",
		PostOrdersSwapFulfillmentsCancel,
	},

	{
		"DeleteGiftCardsGiftCard",
		http.MethodDelete,
		"/admin/gift-cards/:id",
		DeleteGiftCardsGiftCard,
	},

	{
		"GetGiftCards",
		http.MethodGet,
		"/admin/gift-cards",
		GetGiftCards,
	},

	{
		"GetGiftCardsGiftCard",
		http.MethodGet,
		"/admin/gift-cards/:id",
		GetGiftCardsGiftCard,
	},

	{
		"PostGiftCards",
		http.MethodPost,
		"/admin/gift-cards",
		PostGiftCards,
	},

	{
		"PostGiftCardsGiftCard",
		http.MethodPost,
		"/admin/gift-cards/:id",
		PostGiftCardsGiftCard,
	},

	{
		"DeleteInvitesInvite",
		http.MethodDelete,
		"/admin/invites/:invite_id",
		DeleteInvitesInvite,
	},

	{
		"GetInvites",
		http.MethodGet,
		"/admin/invites",
		GetInvites,
	},

	{
		"PostInvites",
		http.MethodPost,
		"/admin/invites",
		PostInvites,
	},

	{
		"PostInvitesInviteAccept",
		http.MethodPost,
		"/admin/invites/accept",
		PostInvitesInviteAccept,
	},

	{
		"PostInvitesInviteResend",
		http.MethodPost,
		"/admin/invites/:invite_id/resend",
		PostInvitesInviteResend,
	},

	{
		"DeleteNotesNote",
		http.MethodDelete,
		"/admin/notes/:id",
		DeleteNotesNote,
	},

	{
		"GetNotes",
		http.MethodGet,
		"/admin/notes",
		GetNotes,
	},

	{
		"GetNotesNote",
		http.MethodGet,
		"/admin/notes/:id",
		GetNotesNote,
	},

	{
		"PostNotes",
		http.MethodPost,
		"/admin/notes",
		PostNotes,
	},

	{
		"PostNotesNote",
		http.MethodPost,
		"/admin/notes/:id",
		PostNotesNote,
	},

	{
		"GetNotifications",
		http.MethodGet,
		"/admin/notifications",
		GetNotifications,
	},

	{
		"PostNotificationsNotificationResend",
		http.MethodPost,
		"/admin/notifications/:id/resend",
		PostNotificationsNotificationResend,
	},

	{
		"GetOrders",
		http.MethodGet,
		"/admin/orders",
		GetOrders,
	},

	{
		"GetOrdersOrder",
		http.MethodGet,
		"/admin/orders/:id",
		GetOrdersOrder,
	},

	{
		"PostOrdersOrder",
		http.MethodPost,
		"/admin/orders/:id",
		PostOrdersOrder,
	},

	{
		"PostOrdersOrderArchive",
		http.MethodPost,
		"/admin/orders/:id/archive",
		PostOrdersOrderArchive,
	},

	{
		"PostOrdersOrderCancel",
		http.MethodPost,
		"/admin/orders/:id/cancel",
		PostOrdersOrderCancel,
	},

	{
		"PostOrdersOrderCapture",
		http.MethodPost,
		"/admin/orders/:id/capture",
		PostOrdersOrderCapture,
	},

	{
		"PostOrdersOrderComplete",
		http.MethodPost,
		"/admin/orders/:id/complete",
		PostOrdersOrderComplete,
	},

	{
		"PostOrdersOrderRefunds",
		http.MethodPost,
		"/admin/orders/:id/refund",
		PostOrdersOrderRefunds,
	},

	{
		"PostOrdersOrderReturns",
		http.MethodPost,
		"/admin/orders/:id/return",
		PostOrdersOrderReturns,
	},

	{
		"PostOrdersOrderShipment",
		http.MethodPost,
		"/admin/orders/:id/shipment",
		PostOrdersOrderShipment,
	},

	{
		"PostOrdersOrderShippingMethods",
		http.MethodPost,
		"/admin/orders/:id/shipping-methods",
		PostOrdersOrderShippingMethods,
	},

	{
		"DeletePriceListsPriceList",
		http.MethodDelete,
		"/admin/price-lists/:id",
		DeletePriceListsPriceList,
	},

	{
		"DeletePriceListsPriceListPricesBatch",
		http.MethodDelete,
		"/admin/price-lists/:id/prices/batch",
		DeletePriceListsPriceListPricesBatch,
	},

	{
		"DeletePriceListsPriceListProductsProductPrices",
		http.MethodDelete,
		"/admin/price-lists/:id/products/:product_id/prices",
		DeletePriceListsPriceListProductsProductPrices,
	},

	{
		"DeletePriceListsPriceListVariantsVariantPrices",
		http.MethodDelete,
		"/admin/price-lists/:id/variants/:variant_id/prices",
		DeletePriceListsPriceListVariantsVariantPrices,
	},

	{
		"GetPriceLists",
		http.MethodGet,
		"/admin/price-lists",
		GetPriceLists,
	},

	{
		"GetPriceListsPriceList",
		http.MethodGet,
		"/admin/price-lists/:id",
		GetPriceListsPriceList,
	},

	{
		"PostPriceListsPriceList",
		http.MethodPost,
		"/admin/price-lists",
		PostPriceListsPriceList,
	},

	{
		"PostPriceListsPriceListPriceList",
		http.MethodPost,
		"/admin/price-lists/:id",
		PostPriceListsPriceListPriceList,
	},

	{
		"PostPriceListsPriceListPricesBatch",
		http.MethodPost,
		"/admin/price-lists/:id/prices/batch",
		PostPriceListsPriceListPricesBatch,
	},

	{
		"DeleteProductsProduct",
		http.MethodDelete,
		"/admin/products/:id",
		DeleteProductsProduct,
	},

	{
		"DeleteProductsProductOptionsOption",
		http.MethodDelete,
		"/admin/products/:id/options/:option_id",
		DeleteProductsProductOptionsOption,
	},

	{
		"DeleteProductsProductVariantsVariant",
		http.MethodDelete,
		"/admin/products/:id/variants/:variant_id",
		DeleteProductsProductVariantsVariant,
	},

	{
		"GetPriceListsPriceListProducts",
		http.MethodGet,
		"/admin/price-lists/:id/products",
		GetPriceListsPriceListProducts,
	},

	{
		"GetProducts",
		http.MethodGet,
		"/admin/products",
		GetProducts,
	},

	{
		"GetProductsProduct",
		http.MethodGet,
		"/admin/products/:id",
		GetProductsProduct,
	},

	{
		"GetProductsProductVariants",
		http.MethodGet,
		"/admin/products/:id/variants",
		GetProductsProductVariants,
	},

	{
		"GetProductsTypes",
		http.MethodGet,
		"/admin/products/types",
		GetProductsTypes,
	},

	{
		"PostProducts",
		http.MethodPost,
		"/admin/products",
		PostProducts,
	},

	{
		"PostProductsProduct",
		http.MethodPost,
		"/admin/products/:id",
		PostProductsProduct,
	},

	{
		"PostProductsProductMetadata",
		http.MethodPost,
		"/admin/products/:id/metadata",
		PostProductsProductMetadata,
	},

	{
		"PostProductsProductOptions",
		http.MethodPost,
		"/admin/products/:id/options",
		PostProductsProductOptions,
	},

	{
		"PostProductsProductOptionsOption",
		http.MethodPost,
		"/admin/products/:id/options/:option_id",
		PostProductsProductOptionsOption,
	},

	{
		"PostProductsProductVariants",
		http.MethodPost,
		"/admin/products/:id/variants",
		PostProductsProductVariants,
	},

	{
		"PostProductsProductVariantsVariant",
		http.MethodPost,
		"/admin/products/:id/variants/:variant_id",
		PostProductsProductVariantsVariant,
	},

	{
		"GetProductTags",
		http.MethodGet,
		"/admin/product-tags",
		GetProductTags,
	},

	{
		"GetProductsTagUsage",
		http.MethodGet,
		"/admin/products/tag-usage",
		GetProductsTagUsage,
	},

	{
		"GetProductTypes",
		http.MethodGet,
		"/admin/product-types",
		GetProductTypes,
	},

	{
		"GetVariants",
		http.MethodGet,
		"/admin/variants",
		GetVariants,
	},

	{
		"DeleteRegionsRegion",
		http.MethodDelete,
		"/admin/regions/:id",
		DeleteRegionsRegion,
	},

	{
		"GetRegions",
		http.MethodGet,
		"/admin/regions",
		GetRegions,
	},

	{
		"GetRegionsRegion",
		http.MethodGet,
		"/admin/regions/:id",
		GetRegionsRegion,
	},

	{
		"GetRegionsRegionFulfillmentOptions",
		http.MethodGet,
		"/admin/regions/:id/fulfillment-options",
		GetRegionsRegionFulfillmentOptions,
	},

	{
		"PostRegions",
		http.MethodPost,
		"/admin/regions",
		PostRegions,
	},

	{
		"PostRegionsRegion",
		http.MethodPost,
		"/admin/regions/:id",
		PostRegionsRegion,
	},

	{
		"PostRegionsRegionCountries",
		http.MethodPost,
		"/admin/regions/:id/countries",
		PostRegionsRegionCountries,
	},

	{
		"PostRegionsRegionCountriesCountry",
		http.MethodDelete,
		"/admin/regions/:id/countries/:country_code",
		PostRegionsRegionCountriesCountry,
	},

	{
		"PostRegionsRegionFulfillmentProviders",
		http.MethodPost,
		"/admin/regions/:id/fulfillment-providers",
		PostRegionsRegionFulfillmentProviders,
	},

	{
		"PostRegionsRegionFulfillmentProvidersProvider",
		http.MethodDelete,
		"/admin/regions/:id/fulfillment-providers/:provider_id",
		PostRegionsRegionFulfillmentProvidersProvider,
	},

	{
		"PostRegionsRegionPaymentProviders",
		http.MethodPost,
		"/admin/regions/:id/payment-providers",
		PostRegionsRegionPaymentProviders,
	},

	{
		"PostRegionsRegionPaymentProvidersProvider",
		http.MethodDelete,
		"/admin/regions/:id/payment-providers/:provider_id",
		PostRegionsRegionPaymentProvidersProvider,
	},

	{
		"GetReturns",
		http.MethodGet,
		"/admin/returns",
		GetReturns,
	},

	{
		"PostOrdersOrderReturns",
		http.MethodPost,
		"/admin/orders/:id/return",
		PostOrdersOrderReturns,
	},

	{
		"PostReturnsReturnCancel",
		http.MethodPost,
		"/admin/returns/:id/cancel",
		PostReturnsReturnCancel,
	},

	{
		"PostReturnsReturnReceive",
		http.MethodPost,
		"/admin/returns/:id/receive",
		PostReturnsReturnReceive,
	},

	{
		"DeleteReturnReason",
		http.MethodDelete,
		"/admin/return-reasons/:id",
		DeleteReturnReason,
	},

	{
		"GetReturnReasons",
		http.MethodGet,
		"/admin/return-reasons",
		GetReturnReasons,
	},

	{
		"GetReturnReasonsReason",
		http.MethodGet,
		"/admin/return-reasons/:id",
		GetReturnReasonsReason,
	},

	{
		"PostReturnReasons",
		http.MethodPost,
		"/admin/return-reasons",
		PostReturnReasons,
	},

	{
		"PostReturnReasonsReason",
		http.MethodPost,
		"/admin/return-reasons/:id",
		PostReturnReasonsReason,
	},

	{
		"DeleteSalesChannelsChannelProductsBatch",
		http.MethodDelete,
		"/admin/sales-channels/:id/products/batch",
		DeleteSalesChannelsChannelProductsBatch,
	},

	{
		"DeleteSalesChannelsSalesChannel",
		http.MethodDelete,
		"/admin/sales-channels/:id",
		DeleteSalesChannelsSalesChannel,
	},

	{
		"GetSalesChannels",
		http.MethodGet,
		"/admin/sales-channels",
		GetSalesChannels,
	},

	{
		"GetSalesChannelsSalesChannel",
		http.MethodGet,
		"/admin/sales-channels/:id",
		GetSalesChannelsSalesChannel,
	},

	{
		"PostSalesChannels",
		http.MethodPost,
		"/admin/sales-channels",
		PostSalesChannels,
	},

	{
		"PostSalesChannelsChannelProductsBatch",
		http.MethodPost,
		"/admin/sales-channels/:id/products/batch",
		PostSalesChannelsChannelProductsBatch,
	},

	{
		"PostSalesChannelsSalesChannel",
		http.MethodPost,
		"/admin/sales-channels/:id",
		PostSalesChannelsSalesChannel,
	},

	{
		"DeleteShippingOptionsOption",
		http.MethodDelete,
		"/admin/shipping-options/:id",
		DeleteShippingOptionsOption,
	},

	{
		"GetShippingOptions",
		http.MethodGet,
		"/admin/shipping-options",
		GetShippingOptions,
	},

	{
		"GetShippingOptionsOption",
		http.MethodGet,
		"/admin/shipping-options/:id",
		GetShippingOptionsOption,
	},

	{
		"PostShippingOptions",
		http.MethodPost,
		"/admin/shipping-options",
		PostShippingOptions,
	},

	{
		"PostShippingOptionsOption",
		http.MethodPost,
		"/admin/shipping-options/:id",
		PostShippingOptionsOption,
	},

	{
		"DeleteShippingProfilesProfile",
		http.MethodDelete,
		"/admin/shipping-profiles/:id",
		DeleteShippingProfilesProfile,
	},

	{
		"GetShippingProfiles",
		http.MethodGet,
		"/admin/shipping-profiles",
		GetShippingProfiles,
	},

	{
		"GetShippingProfilesProfile",
		http.MethodGet,
		"/admin/shipping-profiles/:id",
		GetShippingProfilesProfile,
	},

	{
		"PostShippingProfiles",
		http.MethodPost,
		"/admin/shipping-profiles",
		PostShippingProfiles,
	},

	{
		"PostShippingProfilesProfile",
		http.MethodPost,
		"/admin/shipping-profiles/:id",
		PostShippingProfilesProfile,
	},

	{
		"DeleteStoreCurrenciesCode",
		http.MethodDelete,
		"/admin/store/currencies/:code",
		DeleteStoreCurrenciesCode,
	},

	{
		"GetStore",
		http.MethodGet,
		"/admin/store",
		GetStore,
	},

	{
		"GetStorePaymentProviders",
		http.MethodGet,
		"/admin/store/payment-providers",
		GetStorePaymentProviders,
	},

	{
		"GetStoreTaxProviders",
		http.MethodGet,
		"/admin/store/tax-providers",
		GetStoreTaxProviders,
	},

	{
		"PostStore",
		http.MethodPost,
		"/admin/store",
		PostStore,
	},

	{
		"PostStoreCurrenciesCode",
		http.MethodPost,
		"/admin/store/currencies/:code",
		PostStoreCurrenciesCode,
	},

	{
		"GetSwaps",
		http.MethodGet,
		"/admin/swaps",
		GetSwaps,
	},

	{
		"GetSwapsSwap",
		http.MethodGet,
		"/admin/swaps/:id",
		GetSwapsSwap,
	},

	{
		"PostOrdersOrderSwaps",
		http.MethodPost,
		"/admin/order/:id/swaps",
		PostOrdersOrderSwaps,
	},

	{
		"PostOrdersOrderSwapsSwapProcessPayment",
		http.MethodPost,
		"/admin/orders/:id/swaps/:swap_id/process-payment",
		PostOrdersOrderSwapsSwapProcessPayment,
	},

	{
		"PostOrdersOrderSwapsSwapShipments",
		http.MethodPost,
		"/admin/orders/:id/swaps/:swap_id/shipments",
		PostOrdersOrderSwapsSwapShipments,
	},

	{
		"PostOrdersSwapCancel",
		http.MethodPost,
		"/admin/orders/:id/swaps/:swap_id/cancel",
		PostOrdersSwapCancel,
	},

	{
		"DeleteTaxRatesTaxRate",
		http.MethodDelete,
		"/admin/tax-rates/:id",
		DeleteTaxRatesTaxRate,
	},

	{
		"DeleteTaxRatesTaxRateProductTypes",
		http.MethodDelete,
		"/admin/tax-rates/:id/product-types/batch",
		DeleteTaxRatesTaxRateProductTypes,
	},

	{
		"DeleteTaxRatesTaxRateProducts",
		http.MethodDelete,
		"/admin/tax-rates/:id/products/batch",
		DeleteTaxRatesTaxRateProducts,
	},

	{
		"DeleteTaxRatesTaxRateShippingOptions",
		http.MethodDelete,
		"/admin/tax-rates/:id/shipping-options/batch",
		DeleteTaxRatesTaxRateShippingOptions,
	},

	{
		"GetTaxRates",
		http.MethodGet,
		"/admin/tax-rates",
		GetTaxRates,
	},

	{
		"GetTaxRatesTaxRate",
		http.MethodGet,
		"/admin/tax-rates/:id",
		GetTaxRatesTaxRate,
	},

	{
		"PostTaxRates",
		http.MethodPost,
		"/admin/tax-rates",
		PostTaxRates,
	},

	{
		"PostTaxRatesTaxRate",
		http.MethodPost,
		"/admin/tax-rates/:id",
		PostTaxRatesTaxRate,
	},

	{
		"PostTaxRatesTaxRateProductTypes",
		http.MethodPost,
		"/admin/tax-rates/:id/product-types/batch",
		PostTaxRatesTaxRateProductTypes,
	},

	{
		"PostTaxRatesTaxRateProducts",
		http.MethodPost,
		"/admin/tax-rates/:id/products/batch",
		PostTaxRatesTaxRateProducts,
	},

	{
		"PostTaxRatesTaxRateShippingOptions",
		http.MethodPost,
		"/admin/tax-rates/:id/shipping-options/batch",
		PostTaxRatesTaxRateShippingOptions,
	},

	{
		"PostUploads",
		http.MethodPost,
		"/admin/uploads",
		PostUploads,
	},

	{
		"DeleteUsersUser",
		http.MethodDelete,
		"/admin/users/:id",
		DeleteUsersUser,
	},

	{
		"GetUsers",
		http.MethodGet,
		"/admin/users",
		GetUsers,
	},

	{
		"GetUsersUser",
		http.MethodGet,
		"/admin/users/:id",
		GetUsersUser,
	},

	{
		"PostUsers",
		http.MethodPost,
		"/admin/users",
		PostUsers,
	},

	{
		"PostUsersUser",
		http.MethodPost,
		"/admin/users/:id",
		PostUsersUser,
	},

	{
		"PostUsersUserPassword",
		http.MethodPost,
		"/admin/users/reset-password",
		PostUsersUserPassword,
	},

	{
		"PostUsersUserPasswordToken",
		http.MethodPost,
		"/admin/users/password-token",
		PostUsersUserPasswordToken,
	},
}
