package checkout

type CheckoutSession struct {
	AfterExpiration           NullableCheckoutSessionAfterExpiration            `json:"after_expiration,omitempty"`
	AllowPromotionCodes       NullableBool                                      `json:"allow_promotion_codes,omitempty"`
	AmountSubtotal            int                                               `json:"amount_subtotal,omitempty"`
	AmountTotal               int                                               `json:"amount_total,omitempty"`
	AutomaticTax              PaymentPagesCheckoutSessionAutomaticTax           `json:"automatic_tax"`
	BillingAddressCollection  string                                            `json:"billing_address_collection,omitempty"`
	CancelUrl                 string                                            `json:"cancel_url,omitempty"`
	ClientReferenceId         string                                            `json:"client_reference_id,omitempty"`
	Consent                   NullableCheckoutSessionConsent                    `json:"consent,omitempty"`
	ConsentCollection         NullableCheckoutSessionConsentCollection          `json:"consent_collection,omitempty"`
	Created                   int32                                             `json:"created"`
	Currency                  string                                            `json:"currency,omitempty"`
	CustomText                PaymentPagesCheckoutSessionCustomText             `json:"custom_text"`
	Customer                  NullableCheckoutSessionCustomer                   `json:"customer,omitempty"`
	CustomerCreation          string                                            `json:"customer_creation,omitempty"`
	CustomerDetails           NullableCheckoutSessionCustomerDetails            `json:"customer_details,omitempty"`
	CustomerEmail             string                                            `json:"customer_email,omitempty"`
	ExpiresAt                 int32                                             `json:"expires_at"`
	Id                        string                                            `json:"id"`
	Invoice                   NullableCheckoutSessionInvoice                    `json:"invoice,omitempty"`
	InvoiceCreation           NullableCheckoutSessionInvoiceCreation            `json:"invoice_creation,omitempty"`
	LineItems                 *PaymentPagesCheckoutSessionListLineItems1        `json:"line_items,omitempty"`
	Livemode                  bool                                              `json:"livemode"`
	Locale                    string                                            `json:"locale,omitempty"`
	Metadata                  map[string]string                                 `json:"metadata,omitempty"`
	Mode                      string                                            `json:"mode"`
	Object                    string                                            `json:"object"`
	PaymentIntent             NullableCheckoutSessionPaymentIntent              `json:"payment_intent,omitempty"`
	PaymentLink               NullableCheckoutSessionPaymentLink                `json:"payment_link,omitempty"`
	PaymentMethodCollection   string                                            `json:"payment_method_collection,omitempty"`
	PaymentMethodOptions      NullableCheckoutSessionPaymentMethodOptions1      `json:"payment_method_options,omitempty"`
	PaymentMethodTypes        []string                                          `json:"payment_method_types"`
	PaymentStatus             string                                            `json:"payment_status"`
	PhoneNumberCollection     *PaymentPagesCheckoutSessionPhoneNumberCollection `json:"phone_number_collection,omitempty"`
	RecoveredFrom             string                                            `json:"recovered_from,omitempty"`
	SetupIntent               NullableCheckoutSessionSetupIntent                `json:"setup_intent,omitempty"`
	ShippingAddressCollection NullableCheckoutSessionShippingAddressCollection  `json:"shipping_address_collection,omitempty"`
	ShippingCost              NullableCheckoutSessionShippingCost               `json:"shipping_cost,omitempty"`
	ShippingDetails           NullableCheckoutSessionShippingDetails            `json:"shipping_details,omitempty"`
	ShippingOptions           []PaymentPagesCheckoutSessionShippingOption       `json:"shipping_options"`
	Status                    string                                            `json:"status,omitempty"`
	SubmitType                string                                            `json:"submit_type,omitempty"`
	Subscription              NullableCheckoutSessionSubscription               `json:"subscription,omitempty"`
	SuccessUrl                string                                            `json:"success_url"`
	TaxIdCollection           *PaymentPagesCheckoutSessionTaxIdCollection       `json:"tax_id_collection,omitempty"`
	TotalDetails              NullableCheckoutSessionTotalDetails               `json:"total_details,omitempty"`
	Url                       string                                            `json:"url,omitempty"`
}
