/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type GetTaxRatesRateParameterOneOf struct {

	// filter by rates less than this number
	Lt float32 `json:"lt,omitempty"`

	// filter by rates greater than this number
	Gt float32 `json:"gt,omitempty"`

	// filter by rates less than or equal to this number
	Lte float32 `json:"lte,omitempty"`

	// filter by rates greater than or equal to this number
	Gte float32 `json:"gte,omitempty"`
}
