/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type GetProductsTagUsage200ResponseTagsInner struct {

	// The ID of the tag.
	Id string `json:"id,omitempty"`

	// The number of products that use this tag.
	UsageCount string `json:"usage_count,omitempty"`

	// The value of the tag.
	Value string `json:"value,omitempty"`
}
