/*
 * Medusa Admin API
 *
 * API reference for Medusa's Admin endpoints. All endpoints are prefixed with `/admin`.  ## Authentication  There are two ways to send authenticated requests to the Medusa server: Using a user's API token, or using a Cookie Session ID.  <!-- ReDoc-Inject: <SecurityDefinitions> --> 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type GetCustomerGroupsIdParameterOneOf struct {

	// filter by IDs less than this ID
	Lt string `json:"lt,omitempty"`

	// filter by IDs greater than this ID
	Gt string `json:"gt,omitempty"`

	// filter by IDs less than or equal to this ID
	Lte string `json:"lte,omitempty"`

	// filter by IDs greater than or equal to this ID
	Gte string `json:"gte,omitempty"`
}
