package methods

// PaymentIntentPaymentMethodOptionsInteracPresent struct for PaymentIntentPaymentMethodOptionsInteracPresent
type PaymentIntentPaymentMethodOptionsInteracPresent struct {
	PaymentIntentTypeSpecificPaymentMethodOptionsClient *PaymentIntentTypeSpecificPaymentMethodOptionsClient
}
